"use client"

import { createContext, useState, useEffect, useContext, type ReactNode } from "react"

// Define available languages
export type Language = "en" | "es" | "pt"

// Define the context type
type LanguageContextType = {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

// Create the context with default values
const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key: string) => key,
})

// Translation data
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.dashboard": "Dashboard",
    "nav.healthRecords": "Health Records",
    "nav.healthPlan": "Health Plan",
    "nav.medications": "Medications",
    "nav.messages": "Messages",
    "nav.appointments": "Appointments",
    "nav.permissions": "Permissions",
    "nav.profileSettings": "Profile & Settings",
    "nav.logout": "Logout",
    "nav.healthGoals": "Health Goals",

    // Common actions
    "action.save": "Save",
    "action.cancel": "Cancel",
    "action.add": "Add",
    "action.edit": "Edit",
    "action.delete": "Delete",
    "action.update": "Update",
    "action.connect": "Connect",
    "action.revoke": "Revoke",
    "action.current": "Current",
    "action.submit": "Submit",
    "action.download": "Download",

    // Greetings
    "greeting.morning": "Good morning",
    "greeting.afternoon": "Good afternoon",
    "greeting.evening": "Good evening",

    // Time periods
    "time.morning": "Morning",
    "time.afternoon": "Afternoon",
    "time.evening": "Evening",
    "time.night": "Night",

    // Dashboard
    "dashboard.overview": "Here's an overview of your health journey.",
    "dashboard.healthSummary": "Health Summary",
    "dashboard.healthSummaryDesc": "Your current health status and plan progress",
    "dashboard.overallHealth": "Overall Health",
    "dashboard.planProgress": "Plan Progress",
    "dashboard.latestHealthRecords": "Latest Health Records",
    "dashboard.latestHealthRecordsDesc": "Your most recent health measurements and trends",
    "dashboard.healthMetrics": "Health Metrics",
    "dashboard.wellnessMetrics": "Wellness Metrics",
    "dashboard.previous": "Previous",
    "dashboard.healthPlanProgress": "Health Plan Progress",
    "dashboard.healthPlanProgressDesc": "Your progress towards health goals",
    "dashboard.overallAssessment": "Overall Assessment",
    "dashboard.positive": "Positive",
    "dashboard.improvement": "Improvement",
    "dashboard.keyMetrics": "Key Metrics",
    "dashboard.target": "Target",
    "dashboard.complete": "complete",
    "dashboard.viewAllHealthRecords": "View All Health Records",
    "dashboard.viewFullHealthPlan": "View Full Health Plan",
    "dashboard.upcomingAppointments": "Upcoming Appointments",
    "dashboard.viewAll": "View All",
    "dashboard.forgottenMedsAlert": "You have {count} medication(s) that need attention",
    "dashboard.lastTaken": "Last taken",
    "dashboard.healthAssessment":
      "Your overall health is fair with some areas needing attention. Your blood pressure is slightly elevated and should be monitored.",
    "dashboard.planAssessment":
      "Your health plan is progressing well. Continue with your medication regimen and increase physical activity slightly to meet your goals.",
    "dashboard.planStrengths": "Medication adherence, cholesterol management",
    "dashboard.planImprovements": "Blood pressure control, daily physical activity",
    "dashboard.greatProgress": "Great progress",
    "dashboard.doingWell": "Doing well",
    "dashboard.improvingNeedPush": "Improving but still need to push",
    "dashboard.needImprove": "Need to improve",
    "dashboard.gettingWorse": "Getting worse",
    "dashboard.ahead": "Ahead",
    "dashboard.onTrack": "On track",
    "dashboard.behind": "Behind",
    "dashboard.bloodPressure": "Blood Pressure",
    "dashboard.bloodGlucose": "Blood Glucose",
    "dashboard.totalCholesterol": "Total Cholesterol",
    "dashboard.dailySteps": "Daily Steps",
    "dashboard.sleepDuration": "Sleep Duration",
    "dashboard.stressLevel": "Stress Level",
    "dashboard.physicalActivity": "Physical Activity",
    "dashboard.normalBP": "Normal: <120/80 mmHg",
    "dashboard.normalGlucose": "Normal: 70-99 mg/dL",
    "dashboard.normalCholesterol": "Normal: <200 mg/dL",
    "dashboard.targetSteps": "Target: 10,000 steps",
    "dashboard.targetSleep": "Target: 7-9 hours",
    "dashboard.targetStress": "Target: Low",
    "dashboard.medium": "Medium",
    "dashboard.high": "High",
    "dashboard.status.normal": "Normal",
    "dashboard.status.abnormal": "Abnormal",
    "dashboard.status.good": "Good",
    "dashboard.status.fair": "Fair",
    "dashboard.status.poor": "Poor",
    "dashboard.morning": "Morning",
    "dashboard.evening": "Evening",

    // Health Records
    "health.controlRecords": "Control your health and wellness records to improve your condition!",
    "health.summary": "Summary",
    "health.history": "History",
    "health.analysis": "Analysis",
    "health.body": "Body",
    "health.lifestyle": "Lifestyle",
    "health.vitals": "Vitals",
    "health.genetics": "Genetics",
    "health.images": "Exams",
    "health.overallAssessment": "Overall Health Assessment",
    "health.overallAssessmentDesc": "Your current health status based on all metrics",
    "health.healthScore": "Health Score",
    "health.excellent": "Excellent",
    "health.good": "Good",
    "health.needsImprovement": "Needs Improvement",
    "health.areasOfConcern": "AREAS OF CONCERN",
    "health.positiveTrends": "POSITIVE TRENDS",
    "health.recommendations": "RECOMMENDATIONS",
    "health.ldlConcern":
      "Your LDL cholesterol (125 mg/dL) remains above target despite medication. White blood cell count is elevated (11.2 K/uL), suggesting possible inflammation.",
    "health.bpImprovement":
      "Blood pressure has improved significantly (-13/7 mmHg) and is now closer to target range. Weight has decreased by 7 lbs over 4 months. Blood glucose has normalized at 98 mg/dL.",
    "health.medicationRecommendation":
      "Continue current blood pressure and diabetes medications. Consider increasing statin dosage or adding ezetimibe for cholesterol management. Schedule follow-up CBC in 4 weeks to monitor white blood cell count.",
    "health.healthRecords": "Health Records",
    "health.importantMetrics": "Your most important health metrics",
    "health.wellnessRecords": "Wellness Records",
    "health.lifestyleMetrics": "Your lifestyle and body composition metrics",
    "health.currentConditions": "Current Medical Conditions",
    "health.activeConditions": "Your active health conditions",
    "health.pastConditions": "Past Medical Conditions",
    "health.resolvedConditions": "Your resolved health conditions",
    "health.familyHistory": "Family Medical History",
    "health.familyConditions": "Medical conditions in your family",
    "health.diagnosed": "Diagnosed",
    "health.treatment": "Treatment",
    "health.resolved": "Resolved",
    "health.relation": "Relation",
    "health.outcome": "Outcome",
    "health.ageOfOnset": "Age of onset",
    "health.condition": "Condition",
    "health.statusLabel": "Status",
    "health.notes": "Notes",
    "health.resolvedDate": "Resolved Date",
    "health.editCurrentConditions": "Edit Current Medical Conditions",
    "health.editCurrentConditionsDesc": "Manage your current medical conditions and their status",
    "health.editPastConditions": "Edit Past Medical Conditions",
    "health.editPastConditionsDesc": "Manage your past medical conditions that have been resolved",
    "health.editFamilyHistory": "Edit Family Medical History",
    "health.editFamilyHistoryDesc": "Manage your family medical history",
    "health.status.controlled": "Controlled",
    "health.status.partiallyControlled": "Partially Controlled",
    "health.status.uncontrolled": "Uncontrolled",
    "health.healthAnalysis": "Health Analysis",
    "health.aiInsights": "AI-generated insights from your lab results",
    "health.labDocuments": "Lab Documents",
    "health.recentResults": "Recent test results",
    "health.uploadLabDocument": "Upload Lab Document",
    "health.uploadLabDesc": "Upload a PDF of your lab results and add the date of analysis.",
    "health.date": "Date",
    "health.type": "Type",
    "health.provider": "Provider",
    "health.file": "File",
    "health.clickToUpload": "Click to upload PDF",
    "health.pdfMaxSize": "PDF (max. 10MB)",
    "health.documentUploaded": "Document uploaded successfully!",
    "health.uploadDocument": "Upload Document",
    "health.seeAllDocuments": "See All Documents",
    "health.allLabDocuments": "All Lab Documents",
    "health.addMetric": "Add {category} Metric",
    "health.metric": "Metric",
    "health.value": "Value",
    "health.unit": "Unit",
    "health.metricSaved": "Metric saved successfully!",
    "health.saveMetric": "Save Metric",
    "health.addValue": "Add value",
    "health.newMetric": "New metric",
    "health.createNewMetric": "Create New Metric",
    "health.addCustomMetric": "Add a custom metric to track in your health records.",
    "health.vitaminDExample": "e.g., Vitamin D",
    "health.ngmlExample": "e.g., ng/mL",
    "health.rangeExample": "e.g., 30-80",
    "health.greaterThanExample": "e.g., >15",
    "health.createMetric": "Create Metric",
    "health.bodyCompositionAnalysis": "Body Composition Analysis",
    "health.bodyCompositionDesc": "AI-generated insights from your body composition data",
    "health.bmiConcern": "BMI remains in overweight range at 26.2.",
    "health.bodyFatDecrease":
      "Body fat percentage has decreased by 2.3% over 6 months. Muscle mass has increased by 1.5%. Waist circumference has decreased by 2 inches.",
    "health.exerciseRecommendation":
      "Continue current exercise regimen with emphasis on strength training. Maintain protein intake to support muscle growth. Target additional 5-7 lbs weight loss to reach BMI <25.",
    "health.bodyCompositionMetrics": "Body Composition Metrics",
    "health.bodyMeasurements": "Your body composition measurements and trends",
    "health.addBodyMetric": "Add Body Composition Metric",
    "health.enterBodyMetricDetails": "Enter the details for the new body composition metric.",
    "health.bodyFat": "Body Fat",
    "health.muscleMass": "Muscle Mass",
    "health.bmi": "BMI",
    "health.waistCircumference": "Waist Circumference",
    "health.waistHipRatio": "Waist-Hip Ratio",
    "health.visceralFat": "Visceral Fat",
    "health.createNewBodyMetric": "Create New Body Metric",
    "health.addCustomBodyMetric": "Add a custom body composition metric to track.",
    "health.boneDensityExample": "e.g., Bone Density",
    "health.gcm2Example": "e.g., g/cm²",
    "health.newBodyMetricCreated": "New body metric created successfully!",
    "health.bodyComposition": "Body Composition",
    "health.anthropometric": "Anthropometric",
    "health.fitness": "Fitness",
    "health.lifestyleAnalysis": "Lifestyle Analysis",
    "health.lifestyleInsights": "AI-generated insights from your lifestyle data",
    "health.stepsConcern": "Daily step count averages 6,200, below the recommended 10,000 steps.",
    "health.sleepPositive":
      "Sleep quality is consistently good, averaging 7.2 hours nightly. Workout frequency has increased to 3 sessions weekly.",
    "health.walkingRecommendation":
      "Increase daily walking by adding a 20-minute walk after dinner. Maintain current sleep schedule. Consider adding one additional strength training session per week.",
    "health.lifestyleMeasurements": "Your lifestyle measurements and trends",
    "health.addLifestyleMetric": "Add Lifestyle Metric",
    "health.enterLifestyleDetails": "Enter the details for the new lifestyle metric.",
    "health.sleep": "Sleep",
    "health.steps": "Steps",
    "health.workouts": "Workouts",
    "health.stressLevel": "Stress Level",
    "health.screenTime": "Screen Time",
    "health.nutritionScore": "Nutrition Score",
    "health.createNewLifestyleMetric": "Create New Lifestyle Metric",
    "health.addCustomLifestyleMetric": "Add a custom lifestyle metric to track.",
    "health.meditationExample": "e.g., Meditation",
    "health.minDayExample": "e.g., min/day",
    "health.newLifestyleMetricCreated": "New lifestyle metric created successfully!",
    "health.physicalActivity": "Physical Activity",
    "health.nutrition": "Nutrition",
    "health.mentalWellness": "Mental Wellness",
    "health.habits": "Habits",
    "health.vitalsAnalysis": "Vitals Analysis",
    "health.vitalsInsights": "AI-generated insights from your vital signs",
    "health.vitalsMetrics": "Vitals Metrics",
    "health.vitalsMeasurements": "Your vital sign measurements and trends",
    "health.bloodPressureConcern": "Blood pressure remains slightly elevated at 132/85 mmHg despite improvement.",
    "health.heartRateImprovement":
      "Resting heart rate has decreased to 68 bpm, indicating improved cardiovascular fitness. Oxygen saturation is consistently normal at 98%.",
    "health.medicationExerciseRecommendation":
      "Continue current antihypertensive medication. Increase aerobic exercise to 150 minutes weekly to further improve blood pressure. Monitor blood pressure daily and log readings.",
    "health.vitalSigns": "Vital Signs",
    "health.vitalsTrends": "Your vital sign measurements and trends",
    "health.addVitalSign": "Add Vital Sign",
    "health.enterVitalDetails": "Enter the details for the new vital sign measurement.",
    "health.vitalSignSaved": "Vital sign saved successfully!",
    "health.saveVitalSign": "Save Vital Sign",
    "health.createNewVitalSign": "Create New Vital Sign",
    "health.addCustomVitalSign": "Add a custom vital sign to track.",
    "health.peakFlowExample": "e.g., Peak Flow",
    "health.lminExample": "e.g., L/min",
    "health.newVitalSignCreated": "New vital sign created successfully!",
    "health.cardiovascular": "Cardiovascular",
    "health.respiratory": "Respiratory",
    "health.other": "Other",
    "health.geneticAnalysis": "Genetic Analysis",
    "health.geneticInsights": "Insights from your genetic profile",
    "health.geneticSummary":
      "Your genetic analysis indicates an increased risk for cardiovascular conditions, which aligns with your family history. Your medication response profile suggests good compatibility with your current statin therapy. Consider discussing PCSK9 inhibitors with your doctor if LDL targets aren't met.",
    "health.healthRiskFactors": "Health Risk Factors",
    "health.cardiovascularDisease": "Cardiovascular Disease",
    "health.elevatedRisk": "Elevated Risk",
    "health.averageRisk": "Average Risk",
    "health.alzheimersDisease": "Alzheimer's Disease",
    "health.medicationResponse": "Medication Response",
    "health.statins": "Statins (Atorvastatin)",
    "health.normalResponse": "Normal Response",
    "health.betaBlockers": "Beta Blockers",
    "health.reducedEfficacy": "Reduced Efficacy",
    "health.metformin": "Metformin",
    "health.ssris": "SSRIs",
    "health.geneticReports": "Genetic Reports",
    "health.comprehensiveGeneticPanel": "Comprehensive Genetic Panel",
    "health.pharmacogenomicAnalysis": "Pharmacogenomic Analysis",
    "health.view": "View",
    "health.viewDetails": "View Details",
    "health.reference": "Reference",
    "health.trend": "Trend",
    "health.noTrendData": "No trend data available",
    "health.status.normal": "Normal",
    "health.status.abnormal": "Abnormal",
    "health.ldlCholesterolConcern":
      "LDL cholesterol remains elevated at 125 mg/dL (target <100 mg/dL). White blood cell count is high at 11.2 K/uL, showing mild improvement from previous 12.0 K/uL.",
    "health.cholesterolImprovement":
      "Total cholesterol has decreased to normal range (195 mg/dL). HDL has increased to 50 mg/dL. Glucose has normalized at 98 mg/dL.",
    "health.statinRecommendation":
      "Continue statin therapy, consider dose adjustment. Monitor white blood cell count with follow-up testing in 4 weeks. Maintain current diabetes management approach.",
    "health.weeklyProgress": "Weekly Progress",
    "health.weeklyProgressDescription":
      "You've completed 76% of your weekly health tasks, which is 5% better than last week.",
    "health.currentHealthGoals": "Your current health improvement goals",
    "health.viewAllGoals": "View All Goals",
    "health.dailyTasks": "Daily Tasks",
    "health.dailyActivities": "Your daily health activities",
    "health.viewAllTasks": "View All Tasks",
    "health.personalizedTargets": "Your personalized health improvement targets",
    "health.addNewGoal": "Add New Goal",
    "health.progress": "Progress",
    "health.activitiesDaily": "Activities to complete every day",
    "health.addTask": "Add Task",
    "health.weeklyTasks": "Weekly Tasks",
    "health.activitiesWeekly": "Activities to complete each week",
    "health.monthlyTasks": "Monthly Tasks",
    "health.activitiesMonthly": "Activities to complete each month",
    "health.personalizedRecommendations": "Personalized Recommendations",
    "health.recommendationsDesc": "Suggestions based on your health goals and conditions",
    "health.addRecommendation": "Add Recommendation",
    "health.downloadRecommendations": "Download Full Recommendations",
    "health.current": "Current",
    "health.monitoring": "Monitoring",
    "health.healthcare": "Healthcare",
    "health.planning": "Planning",
    "health.tasks": "Tasks & Activities",
    "health.analysisOverview": "Health Analysis Metrics",
    "health.analysisDescription": "View and manage your health records, metrics, and data trends",

    // Health Images
    "health.images.medicalImages": "Medical Images",
    "health.images.aiSummary": "AI Summary",
    "health.images.aiSummaryContent":
      "Based on your recent imaging studies, most findings are within normal limits. Your chest X-ray shows no acute abnormalities, and brain MRI is normal. However, attention should be given to the small pulmonary nodules found on CT scan - follow-up imaging in 3 months is recommended. The mild degenerative changes in your spine and knee are age-appropriate but may benefit from physical therapy if symptoms persist.",
    "health.images.uploadImage": "Upload Image",
    "health.images.uploadNewImage": "Upload New Medical Image",
    "health.images.uploadDescription": "Upload a medical image report and provide the necessary details.",
    "health.images.imageType": "Image Type",
    "health.images.selectImageType": "Select image type",
    "health.images.bodyPart": "Body Part",
    "health.images.bodyPartPlaceholder": "e.g., Chest, Left Knee, Brain",
    "health.images.imageDate": "Image Date",
    "health.images.findings": "Findings",
    "health.images.selectFindings": "Select findings",
    "health.images.conclusions": "Conclusions",
    "health.images.conclusionsPlaceholder": "Enter the medical conclusions from the report",
    "health.images.uploadFile": "Upload File",
    "health.images.dragDropOrClick": "Drag and drop your file here, or click to browse",
    "health.images.supportedFormats": "Supported formats: PDF, JPG, PNG, DICOM",
    "health.images.xray": "X-Ray",
    "health.images.ultrasound": "Ultrasound",
    "health.images.mri": "MRI",
    "health.images.ctScan": "CT Scan",
    "health.images.others": "Others",
    "health.images.noFindings": "No Findings",
    "health.images.lowRiskFindings": "Low Risk Findings",
    "health.images.relevantFindings": "Relevant Findings",
    "health.images.noImagesInCategory": "No images in this category yet",
    "health.images.view": "View",
    "health.images.reportConclusions": "Report Conclusions",
    "health.images.medicalConclusions": "Medical Conclusions",
    "health.images.viewFullReport": "View Full Report",

    // Health metrics
    "health.metrics.bloodPressure": "Blood Pressure",
    "health.metrics.bloodGlucose": "Blood Glucose",
    "health.metrics.ldlCholesterol": "LDL Cholesterol",
    "health.metrics.heartRate": "Heart Rate",
    "health.metrics.oxygenSaturation": "O₂ Saturation",
    "health.metrics.whiteBloodCells": "White Blood Cells",
    "health.metrics.weight": "Weight",
    "health.metrics.bodyFat": "Body Fat",
    "health.metrics.sleep": "Sleep",
    "health.metrics.steps": "Steps",
    "health.metrics.workouts": "Workouts",
    "health.metrics.nutritionScore": "Nutrition Score",
    "health.metrics.redBloodCells": "Red Blood Cells",
    "health.metrics.hemoglobin": "Hemoglobin",
    "health.metrics.platelets": "Platelets",
    "health.metrics.hematocrit": "Hematocrit",
    "health.metrics.totalCholesterol": "Total Cholesterol",
    "health.metrics.hdlCholesterol": "HDL Cholesterol",
    "health.metrics.triglycerides": "Triglycerides",
    "health.metrics.totalHdlRatio": "Total/HDL Ratio",
    "health.metrics.glucose": "Glucose",
    "health.metrics.hemoglobinA1C": "Hemoglobin A1C",
    "health.metrics.tsh": "TSH",
    "health.metrics.t4Free": "T4 Free",
    "health.metrics.insulin": "Insulin",
    "health.metrics.bun": "BUN",
    "health.metrics.creatinine": "Creatinine",
    "health.metrics.egfr": "eGFR",
    "health.metrics.bunCreatinineRatio": "BUN/Creatinine Ratio",
    "health.metrics.uricAcid": "Uric Acid",
    "health.metrics.sodium": "Sodium",
    "health.metrics.potassium": "Potassium",
    "health.metrics.calcium": "Calcium",
    "health.metrics.chloride": "Chloride",
    "health.metrics.magnesium": "Magnesium",
    "health.metrics.protein": "Protein",
    "health.metrics.ketones": "Ketones",
    "health.metrics.ph": "pH",
    "health.metrics.specificGravity": "Specific Gravity",
    "health.metrics.muscleMass": "Muscle Mass",
    "health.metrics.bmi": "BMI",
    "health.metrics.waistCircumference": "Waist Circumference",
    "health.metrics.waistHipRatio": "Waist-Hip Ratio",
    "health.metrics.visceralFat": "Visceral Fat",
    "health.metrics.stressLevel": "Stress Level",
    "health.metrics.screenTime": "Screen Time",
    "health.metrics.respiratoryRate": "Respiratory Rate",
    "health.metrics.temperature": "Temperature",
    "health.metrics.medication": "Medication",

    // Health categories
    "health.categories.hematology": "Hematology",
    "health.categories.biochemistry": "Biochemistry",
    "health.categories.endocrinology": "Endocrinology",
    "health.categories.kidneyfunction": "Kidney Function",
    "health.categories.electrolytes": "Electrolytes",
    "health.categories.urinalysis": "Urinalysis",

    // Health values
    "health.values.negative": "Negative",
    "health.values.positive": "Positive",
    "health.values.moderate": "Moderate",
    "health.values.low": "Low",

    // Health changes
    "health.changes.noChange": "No change",

    // Health units
    "health.units.inches": "inches",
    "health.units.hours": "hrs",
    "health.units.week": "week",
    "health.units.level": "level",
    "health.units.hoursPerDay": "hrs/day",
    "health.units.points": "points",
    "health.units.breathsPerMinute": "breaths/min",

    // Health documents
    "health.documents.completeBloodCount": "Complete Blood Count",
    "health.documents.comprehensiveMetabolicPanel": "Comprehensive Metabolic Panel",
    "health.documents.lipidPanel": "Lipid Panel",
    "health.documents.hemoglobinA1C": "Hemoglobin A1C",
    "health.documents.urinalysis": "Urinalysis",
    "health.documents.thyroidPanel": "Thyroid Panel",

    // Health document types
    "health.documentTypes.labResults": "Lab Results",

    // Health dates
    "health.dates.april152023": "April 15, 2023",
    "health.dates.january152023": "January 15, 2023",
    "health.dates.october102022": "October 10, 2022",
    "health.dates.january2020": "January 2020",
    "health.dates.february2020": "February 2020",
    "health.dates.november2022": "November 2022",
    "health.dates.december2022": "December 2022",
    "health.dates.june2021": "June 2021",
    "health.dates.august2021": "August 2021",

    // Health conditions
    "health.conditions.hypertension": "Hypertension",
    "health.conditions.hyperlipidemia": "Hyperlipidemia",
    "health.conditions.type2Diabetes": "Type 2 Diabetes",
    "health.conditions.acuteBronchitis": "Acute Bronchitis",
    "health.conditions.ankleSprainRight": "Ankle Sprain (Right)",
    "health.conditions.coronaryArteryDisease": "Coronary Artery Disease",
    "health.conditions.breastCancer": "Breast Cancer",

    // Health relations
    "health.relations.father": "Father",
    "health.relations.mother": "Mother",
    "health.relations.fatherMother": "Father, Mother",
    "health.relations.maternalAunt": "Maternal Aunt",

    // Health age ranges
    "health.ageRanges.fifties": "50s",

    // Health outcomes
    "health.outcomes.managedMedicationStents": "Managed with medication and stents",
    "health.outcomes.managedMedicationDiet": "Managed with medication and diet",
    "health.outcomes.controlledMedication": "Controlled with medication",
    "health.outcomes.successfullyTreated": "Successfully treated, in remission",

    // Health notes
    "health.notes.bloodPressureImproved":
      "Blood pressure has improved significantly with medication and lifestyle changes.",
    "health.notes.ldlElevated": "LDL remains slightly elevated despite medication. May need dosage adjustment.",
    "health.notes.glucoseNormalized": "Blood glucose has normalized with current treatment plan.",
    "health.notes.fullyResolved": "Fully resolved with no complications.",
    "health.notes.fullyHealed": "Fully healed with no residual issues.",

    // Health frequency
    "health.frequency.daily": "daily",
    "health.frequency.twiceDaily": "twice daily",

    // Health treatment
    "health.treatment.dietExercise": "diet and exercise",
    "health.treatment.antibioticsRest": "Antibiotics, rest",
    "health.treatment.ricePhysicalTherapy": "RICE protocol, physical therapy",

    // AI summaries
    "health.aiSummary.overall":
      "AREAS OF CONCERN: Your LDL cholesterol (125 mg/dL) remains above target despite medication. White blood cell count is elevated (11.2 K/uL), suggesting possible inflammation. POSITIVE TRENDS: Blood pressure has improved significantly (-13/7 mmHg) and is now closer to target range. Weight has decreased by 7 lbs over 4 months. Blood glucose has normalized at 98 mg/dL. RECOMMENDATIONS: Continue current blood pressure and diabetes medications. Consider increasing statin dosage or adding ezetimibe for cholesterol management. Schedule follow-up CBC in 4 weeks to monitor white blood cell count.",
    "health.aiSummary.bloodTests":
      "AREAS OF CONCERN: LDL cholesterol remains elevated at 125 mg/dL (target <100 mg/dL). White blood cell count is high at 11.2 K/uL, showing mild improvement from previous 12.0 K/uL. POSITIVE TRENDS: Total cholesterol has decreased to normal range (195 mg/dL). HDL has increased to 50 mg/dL. Glucose has normalized at 98 mg/dL. RECOMMENDATIONS: Continue statin therapy, consider dose adjustment. Monitor white blood cell count with follow-up testing in 4 weeks. Maintain current diabetes management approach.",
    "health.aiSummary.bodyComposition":
      "AREAS OF CONCERN: BMI remains in overweight range at 26.2. POSITIVE TRENDS: Body fat percentage has decreased by 2.3% over 6 months. Muscle mass has increased by 1.5%. Waist circumference has decreased by 2 inches. RECOMMENDATIONS: Continue current exercise regimen with emphasis on strength training. Maintain protein intake to support muscle growth. Target additional 5-7 lbs weight loss to reach BMI <25.",
    "health.aiSummary.vitals":
      "AREAS OF CONCERN: Blood pressure remains slightly elevated at 132/85 mmHg despite improvement. POSITIVE TRENDS: Resting heart rate has decreased to 68 bpm, indicating improved cardiovascular fitness. Oxygen saturation is consistently normal at 98%. RECOMMENDATIONS: Continue current antihypertensive medication. Increase aerobic exercise to 150 minutes weekly to further improve blood pressure. Monitor blood pressure daily and log readings.",
    "health.aiSummary.lifestyle":
      "AREAS OF CONCERN: Daily step count averages 6,200, below the recommended 10,000 steps. POSITIVE TRENDS: Sleep quality is consistently good, averaging 7.2 hours nightly. Workout frequency has increased to 3 sessions weekly. RECOMMENDATIONS: Increase daily walking by adding a 20-minute walk after dinner. Maintain current sleep schedule. Consider adding one additional strength training session per week.",

    "tabs.profile": "Profile",
    "tabs.emergency": "Emergency",
    "tabs.insurance": "Insurance",
    "tabs.security": "Security",
    "tabs.notifications": "Notifications",
    "tabs.integrations": "Integrations",
    "tabs.preferences": "Preferences",
    "tabs.privacy": "Privacy",

    "profile.fullName": "Full Name",
    "profile.email": "Email",
    "profile.phone": "Phone",
    "profile.dob": "Date of Birth",
    "profile.height": "Height",
    "profile.weight": "Weight",
    "profile.address": "Address",
    "profile.medicalNotes": "Medical Notes",
    "profile.medicalNotesDesc": "This information will be shared with your healthcare providers",
    "profile.updateProfile": "Update Profile",
    "profile.manageProfile": "Manage your profile and application settings",

    "emergency.contacts": "Emergency Contacts",
    "emergency.primaryContact": "Primary Contact",
    "emergency.secondaryContact": "Secondary Contact",
    "emergency.phoneNumber": "Phone Number",
    "emergency.medicalInfo": "Medical Information",
    "emergency.bloodType": "Blood Type",
    "emergency.allergies": "Allergies",
    "emergency.medicalConditions": "Medical Conditions",
    "emergency.saveInfo": "Save Information",

    "insurance.primary": "Primary Insurance",
    "insurance.secondary": "Secondary Insurance",
    "insurance.provider": "Insurance Provider",
    "insurance.policyNumber": "Policy Number",
    "insurance.groupNumber": "Group Number",
    "insurance.memberId": "Member ID",
    "insurance.addInsurance": "Add Insurance",
    "insurance.uploadCard": "Upload Card",
    "insurance.saveInfo": "Save Information",

    "security.password": "Password",
    "security.currentPassword": "Current Password",
    "security.newPassword": "New Password",
    "security.confirmPassword": "Confirm Password",
    "security.twoFactor": "Two-Factor Authentication",
    "security.authenticatorApp": "Authenticator App",
    "security.authenticatorDesc": "Use an authenticator app to generate time-based one-time passwords",
    "security.loginSessions": "Login Sessions",
    "security.currentSession": "Current Session",
    "security.previousSession": "Previous Session",
    "security.saveSettings": "Save Settings",

    "notifications.email": "Email Notifications",
    "notifications.emailDesc": "Receive appointment reminders via email",
    "notifications.medicationDesc": "Receive medication reminders via email",
    "notifications.resultsDesc": "Receive test results via email",
    "notifications.newsletterDesc": "Receive monthly newsletter and health tips",
    "notifications.sms": "SMS Notifications",
    "notifications.smsAppointmentDesc": "Receive appointment reminders via SMS",
    "notifications.smsMedicationDesc": "Receive medication reminders via SMS",
    "notifications.smsResultsDesc": "Receive test results via SMS",
    "notifications.push": "Push Notifications",
    "notifications.pushAppointmentDesc": "Receive appointment reminders via push notifications",
    "notifications.pushMedicationDesc": "Receive medication reminders via push notifications",
    "notifications.pushResultsDesc": "Receive test results via push notifications",
    "notifications.appointmentReminders": "Appointment Reminders",
    "notifications.medicationReminders": "Medication Reminders",
    "notifications.testResults": "Test Results",
    "notifications.newsletter": "Newsletter",
    "notifications.savePreferences": "Save Preferences",

    "integrations.healthFitness": "Health & Fitness Integrations",
    "integrations.syncDesc": "Sync your health data from these services",
    "integrations.newIntegration": "New Integration",
    "integrations.addNew": "Add New Integration",
    "integrations.connectDesc": "Connect your account to sync health data",
    "integrations.partner": "Integration Partner",
    "integrations.appleHealth": "Apple Health",
    "integrations.appleHealthDesc": "Sync data from Apple Health",
    "integrations.googleFit": "Google Fit",
    "integrations.googleFitDesc": "Sync data from Google Fit",
    "integrations.withings": "Withings",
    "integrations.withingsDesc": "Sync data from Withings devices",
    "integrations.fitbit": "Fitbit",
    "integrations.fitbitDesc": "Sync data from Fitbit devices",
    "integrations.garmin": "Garmin",
    "integrations.garminDesc": "Sync data from Garmin devices",
    "integrations.ouraRing": "Oura Ring",
    "integrations.ouraRingDesc": "Sync data from Oura Ring",
    "integrations.saveSettings": "Save Settings",

    "preferences.theme": "Theme",
    "preferences.light": "Light",
    "preferences.dark": "Dark",
    "preferences.system": "System",
    "preferences.accessibility": "Accessibility",
    "preferences.textSize": "Text Size",
    "preferences.reduceMotion": "Reduce Motion",
    "preferences.reduceMotionDesc": "Minimize animations throughout the application",
    "preferences.highContrast": "High Contrast",
    "preferences.highContrastDesc": "Increase contrast for better readability",
    "preferences.language": "Language",
    "preferences.timezone": "Time Zone",
    "preferences.units": "Units",
    "preferences.imperial": "Imperial (lbs, in, F)",
    "preferences.metric": "Metric (kg, cm, C)",
    "preferences.savePreferences": "Save Preferences",
    "preferences.savedSuccessfully": "Preferences saved successfully!",
    "preferences.savedSuccessfullyDesc": "Your preferences have been updated.",

    "privacy.settings": "Privacy Settings",
    "privacy.dataSharing": "Data Sharing",
    "privacy.dataSharingDesc": "Share anonymized data to improve healthcare services",
    "privacy.research": "Research Participation",
    "privacy.researchDesc": "Participate in health research studies",
    "privacy.analytics": "Analytics",
    "privacy.analyticsDesc": "Allow usage analytics to improve the application",
    "privacy.saveSettings": "Save Settings",
    "privacy.dataManagement": "Data Management",
    "privacy.requestData": "Request Data Export",
    "privacy.dataRequest": "Data Request",
    "privacy.dataRequestDesc": "Request a copy of your data or deletion of your account",
    "privacy.requestType": "Request Type",
    "privacy.dataExport": "Data Export",
    "privacy.dataDeletion": "Data Deletion",
    "privacy.accountDeletion": "Account Deletion",
    "privacy.reason": "Reason for Request",
    "privacy.reasonPlaceholder": "Please provide a reason for your request",
    "privacy.emailDownload": "Email for Download Link",
    "privacy.emailDownloadDesc": "We'll send a secure download link to this email",

    // Permissions Page
    "permissions.manageDataSharing": "Manage your data sharing permissions",
    "permissions.sharedAccess": "Shared Access",
    "permissions.revokedAccess": "Revoked Access",
    "permissions.accessLogs": "Access Logs",
    "permissions.dataSharing": "Data Sharing",
    "permissions.peopleWithAccess": "People with Access",
    "permissions.grantNewAccess": "Grant New Access",
    "permissions.search": "Search...",
    "permissions.filterByType": "Filter by type",
    "permissions.allContacts": "All Contacts",
    "permissions.healthProfessionals": "Health Professionals",
    "permissions.familyFriends": "Family & Friends",
    "permissions.status.active": "Active",
    "permissions.status.pending": "Pending",
    "permissions.status.revoked": "Revoked",
    "permissions.accessLevel": "Access Level",
    "permissions.permissionsLabel": "Permissions",
    "permissions.viewMedicalHistory": "View Medical History",
    "permissions.downloadMedicalHistory": "Download Medical History",
    "permissions.viewHealthRecords": "View Health Records",
    "permissions.downloadHealthRecords": "Download Health Records",
    "permissions.viewMedications": "View Medications",
    "permissions.viewAppointments": "View Appointments",
    "permissions.lastAccessed": "Last Accessed",
    "permissions.expires": "Expires",
    "permissions.manage": "Manage",
    "permissions.revoke": "Revoke",
    "permissions.revokedAccessDesc": "People who previously had access to your health information",
    "permissions.noRevokedAccess": "No Revoked Access",
    "permissions.noRevokedAccessDesc": "You haven't revoked access for anyone yet.",
    "permissions.revokedOn": "Revoked On",
    "permissions.restoreAccess": "Restore Access",
    "permissions.accessHistory": "Access History",
    "permissions.accessHistoryDesc": "Review who has accessed your health information",
    "permissions.searchAccessLogs": "Search access logs...",
    "permissions.exportLogs": "Export Logs",
    "permissions.filterByTime": "Filter by time",
    "permissions.allTime": "All Time",
    "permissions.today": "Today",
    "permissions.thisWeek": "This Week",
    "permissions.thisMonth": "This Month",
    "permissions.user": "User",
    "permissions.action": "Action",
    "permissions.dateTime": "Date & Time",
    "permissions.status": "Status",
    "permissions.authorized": "Authorized",
    "permissions.unauthorized": "Unauthorized",
    "permissions.showingEntries": "Showing {count} of {total} entries",
    '\
    "permissions.showingEntries': "Showing {count} of {total} entries",
    "permissions.previous": "Previous",
    "permissions.next": "Next",
    "permissions.important": "Important",
    "permissions.dataSharingImportantDesc":
      "These settings control how your health information is shared with healthcare providers and third parties.",
    "permissions.healthDataSharing": "Health Data Sharing",
    "permissions.healthDataSharingDesc":
      "Control how your health data is shared with healthcare providers and third parties",
    "permissions.shareHealthData": "Share Health Data",
    "permissions.shareHealthDataDesc": "Allow sharing your health data with your primary care physician",
    "permissions.shareWithOtherProviders": "Share with Other Providers",
    "permissions.shareWithOtherProvidersDesc": "Allow sharing your health data with other healthcare providers",
    "permissions.shareWithResearchers": "Share with Researchers",
    "permissions.shareWithResearchersDesc": "Allow anonymously sharing your health data for research purposes",
    "permissions.shareWithInsurance": "Share with Insurance",
    "permissions.shareWithInsuranceDesc": "Allow sharing your health data with your insurance provider",
    "permissions.addNewContact": "Add New Contact",
    "permissions.addNewContactDesc": "Add a person who can access your health information",
    "permissions.contactType": "Contact Type",
    "permissions.selectType": "Select type",
    "permissions.doctor": "Doctor",
    "permissions.hospital": "Hospital",
    "permissions.familyMember": "Family Member",
    "permissions.caregiver": "Caregiver",
    "permissions.insuranceProvider": "Insurance Provider",
    "permissions.enterFullName": "Enter full name",
    "permissions.enterEmailAddress": "Enter email address",
    "permissions.relationship": "Relationship",
    "permissions.relationshipPlaceholder": "e.g., Spouse, Parent, Friend",
    "permissions.selectPermissionsDesc": "Select what this contact can access and what actions they can perform",
    "permissions.category": "Category",
    "permissions.view": "View",
    "permissions.download": "Download",
    "permissions.edit": "Edit",
    "permissions.medicalHistory": "Medical History",
    "permissions.healthRecords": "Health Records",
    "permissions.healthPlan": "Health Plan",
    "permissions.medications": "Medications",
    "permissions.appointments": "Appointments",
    "permissions.messages": "Messages",
    "permissions.addContact": "Add Contact",
    "permissions.manageAccess": "Manage Access",
    "permissions.updateAccessFor": "Update access permissions for {name}",
    "permissions.updatePermissionsDesc": "Update what this contact can access and what actions they can perform",
    "permissions.saveChanges": "Save Changes",
    "permissions.revokeAccess": "Revoke Access",
    "permissions.revokeConfirmation":
      "Are you sure you want to revoke access for {name}? They will no longer be able to view or modify your health information.",

    // Messages page
    "messages.communicateWithTeam": "Communicate with your healthcare team",
    "messages.newMessage": "New Message",
    "messages.newMessageDesc": "Create a new message to send to your healthcare provider.",
    "messages.to": "To",
    "messages.subject": "Subject",
    "messages.message": "Message",
    "messages.sendMessage": "Send Message",
    "messages.all": "All",
    "messages.doctors": "Doctors",
    "messages.unread": "Unread",
    "messages.typePlaceholder": "Type your message...",
    "messages.send": "Send",
    "messages.selectConversation": "Select a conversation to view",

    // Medications page
    "medications.greeting": "Good morning, {name}!",
    "medications.manageReminders": "Manage your medications and reminders",
    "medications.addMedication": "Add Medication",
    "medications.currentMedications": "Current Medications",
    "medications.previousMedications": "Previous Medications",
    "medications.purpose": "Purpose",
    "medications.prescribedBy": "Prescribed By",
    "medications.startDate": "Start Date",
    "medications.endDate": "End Date",
    "medications.endNow": "End Now",
    "medications.refillDate": "Refill Date",
    "medications.prescriptionInfo": "Prescription Information",
    "medications.viewRx": "View Rx",
    "medications.rxNumber": "Rx Number",
    "medications.pharmacy": "Pharmacy",
    "medications.quantity": "Quantity",
    "medications.refillsRemaining": "Refills Remaining",
    "medications.lastFilled": "Last Filled",
    "medications.instructions": "Instructions",
    "medications.reminders": "Reminders",
    "medications.add": "Add",
    "medications.noRemindersSet": "No reminders set",
    "medications.daily": "Daily",
    "medications.addMedicationReminder": "Add Medication Reminder",
    "medications.reminderDescription":
      "Set a reminder to take your medication. You'll receive a notification at the specified time.",
    "medications.time": "Time",
    "medications.days": "Days",
    "medications.saveReminder": "Save Reminder",
    "medications.prescriptionDetails": "Prescription Details",
    "medications.prescriptionDescription": "View and download your prescription information.",
    "medications.datePrescribed": "Date Prescribed",
    "medications.originalQuantity": "Original Quantity",
    "medications.refillsAuthorized": "Refills Authorized",
    "medications.prescriber": "Prescriber",
    "medications.downloadPDF": "Download PDF",
    "medications.messageDoctor": "Message Doctor about Medication",
    "medications.messageDescription": "Send a message to your doctor about {name}.",
    "medications.regarding": "Regarding",
    "medications.includeQuestions": "Include any questions or concerns about this medication",
    "medications.typicallyResponds": "Typically responds within 24 hours",
    "medications.sendMessage": "Send Message",
    "medications.editMedication": "Edit Medication",
    "medications.editDescription": "Update the details of your medication.",
    "medications.dosage": "Dosage",
    "medications.frequency": "Frequency",
    "medications.saveChanges": "Save Changes",
    "medications.addNewMedication": "Add New Medication",
    "medications.enterDetails": "Enter the details of your new medication.",
    "medications.name": "Name",
    "medications.namePlaceholder": "Enter medication name",
    "medications.dosagePlaceholder": "Enter dosage (e.g., 10mg)",
    "medications.frequencyPlaceholder": "Enter frequency (e.g., Once daily)",
    "medications.purposePlaceholder": "What is this medication for?",
    "medications.prescribedByPlaceholder": "Doctor's name",
    "medications.instructionsPlaceholder": "Enter instructions",
    "medications.prescription": "Prescription",
    "medications.rxNumberPlaceholder": "Prescription number",
    "medications.pharmacyPlaceholder": "Pharmacy name",
    "medications.quantityPlaceholder": "Original quantity",
    "medications.refillsRemainingPlaceholder": "Number of refills",
    "medications.reasonEnded": "Reason Ended",

    // Appointments page
    "appointments.manageUpcoming": "Manage your upcoming appointments",
    "appointments.bookNew": "Book New Appointment",
    "appointments.fillDetails": "Fill in the details to schedule a new appointment with your healthcare provider.",
    "appointments.doctor": "Doctor",
    "appointments.selectDoctor": "Select a doctor",
    "appointments.date": "Date",
    "appointments.time": "Time",
    "appointments.type": "Type",
    "appointments.selectType": "Select appointment type",
    "appointments.inPerson": "In-Person",
    "appointments.virtual": "Virtual",
    "appointments.phone": "Phone",
    "appointments.reason": "Reason",
    "appointments.reasonPlaceholder": "Reason for visit",
    "appointments.book": "Book Appointment",
    "appointments.reschedule": "Reschedule Appointment",
    "appointments.rescheduleWith": "Reschedule your appointment with",
    "appointments.newDate": "New Date",
    "appointments.newTime": "New Time",
    "appointments.virtualCopay": "($20 copay)",
    "appointments.inPersonCopay": "($40 copay)",
    "appointments.phoneCopay": "($20 copay)",
    "appointments.confirmReschedule": "Confirm Reschedule",
    "appointments.cancelAppointment": "Cancel Appointment",
    "appointments.cancelConfirmation":
      "Are you sure you want to proceed with the cancellation? This action cannot be undone.",
    "appointments.keepAppointment": "No, keep appointment",
    "appointments.confirmCancel": "Yes, cancel appointment",
    "appointments.upcoming": "Upcoming",
    "appointments.past": "Past",
    "appointments.cancelled": "Cancelled",
    "appointments.noUpcoming": "No Upcoming Appointments",
    "appointments.noUpcomingDesc": "You don't have any upcoming appointments scheduled.",
    "appointments.noPast": "No Past Appointments",
    "appointments.noPastDesc": "You don't have any past appointments.",
    "appointments.noCancelled": "No Cancelled Appointments",
    "appointments.noCancelledDesc": "You don't have any cancelled appointments.",
    "appointments.cancelledToast": "Appointment Cancelled",
    "appointments.cancelledToastDesc": "Your appointment has been successfully cancelled.",
    "appointments.rescheduledToast": "Appointment Rescheduled",
    "appointments.rescheduledToastDesc": "Your appointment has been rescheduled for {date} at {time}",
    "appointments.joiningToast": "Joining Video Call",
    "appointments.joiningToastDesc": "Connecting to your virtual appointment...",
    "appointments.connectedToast": "Video Call Connected",
    "appointments.connectedToastDesc": "You are now connected with your healthcare provider.",

    // Dropdown menu items
    "dropdown.profile": "Profile",
    "dropdown.settings": "Settings",
    "dropdown.logout": "Logout",
    "dropdown.addValue": "Add value",
    "dropdown.addDocument": "Add Document",
    "dropdown.analysis": "Analysis",
    "dropdown.cardio": "Cardiology",
    "dropdown.images": "Images",
    "dropdown.genetics": "Genetics",

    "notifications.title": "Notifications",
    "notifications.markAllAsRead": "Mark all as read",
    "notifications.noNotifications": "No new notifications",
    "notifications.new_message_title": "New message",
    "notifications.new_message_description": "You have received a new message from your doctor",
    "notifications.appointment_reminder_title": "Appointment reminder",
    "notifications.appointment_reminder_description": "You have an appointment tomorrow at 10:00 AM",
    "notifications.medication_reminder_title": "Medication reminder",
    "notifications.medication_reminder_description": "Time to take your medication",
  },
  es: {
    // Navigation
    "nav.dashboard": "Panel",
    "nav.healthRecords": "Registros de Salud",
    "nav.healthPlan": "Plan de Salud",
    "nav.medications": "Medicamentos",
    "nav.messages": "Mensajes",
    "nav.appointments": "Citas",
    "nav.permissions": "Permisos",
    "nav.profileSettings": "Perfil y Configuración",
    "nav.logout": "Cerrar Sesión",
    "nav.healthGoals": "Objetivos de Salud",

    // Common actions
    "action.save": "Guardar",
    "action.cancel": "Cancelar",
    "action.add": "Añadir",
    "action.edit": "Editar",
    "action.delete": "Eliminar",
    "action.update": "Actualizar",
    "action.connect": "Conectar",
    "action.revoke": "Revocar",
    "action.current": "Actual",
    "action.submit": "Enviar",
    "action.download": "Descargar",

    // Greetings
    "greeting.morning": "Buenos días",
    "greeting.afternoon": "Buenas tardes",
    "greeting.evening": "Buenas noches",

    // Health Records
    "health.controlRecords": "¡Controla tus registros de salud y bienestar para mejorar tu condición!",
    "health.summary": "Resumen",
    "health.history": "Historial",
    "health.analysis": "Análisis",
    "health.body": "Cuerpo",
    "health.lifestyle": "Estilo de Vida",
    "health.vitals": "Signos Vitales",
    "health.genetics": "Genética",
    "health.images": "Exámenes",

    // Health Images
    "health.images.medicalImages": "Imágenes Médicas",
    "health.images.aiSummary": "Resumen IA",
    "health.images.aiSummaryContent":
      "Basándose en sus estudios de imagen recientes, la mayoría de los hallazgos están dentro de los límites normales. Su radiografía de tórax no muestra anomalías agudas, y la resonancia magnética cerebral es normal. Sin embargo, se debe prestar atención a los pequeños nódulos pulmonares encontrados en la tomografía computarizada: se recomienda seguimiento con imágenes en 3 meses. Los cambios degenerativos leves en su columna vertebral y rodilla son apropiados para la edad, pero pueden beneficiarse de fisioterapia si los síntomas persisten.",
    "health.images.uploadImage": "Subir Imagen",
    "health.images.uploadNewImage": "Subir Nueva Imagen Médica",
    "health.images.uploadDescription": "Sube un informe de imagen médica y proporciona los detalles necesarios.",
    "health.images.imageType": "Tipo de Imagen",
    "health.images.selectImageType": "Seleccionar tipo de imagen",
    "health.images.bodyPart": "Parte del Cuerpo",
    "health.images.bodyPartPlaceholder": "ej., Tórax, Rodilla Izquierda, Cerebro",
    "health.images.imageDate": "Fecha de la Imagen",
    "health.images.findings": "Hallazgos",
    "health.images.selectFindings": "Seleccionar hallazgos",
    "health.images.conclusions": "Conclusiones",
    "health.images.conclusionsPlaceholder": "Ingrese las conclusiones médicas del informe",
    "health.images.uploadFile": "Subir Archivo",
    "health.images.dragDropOrClick": "Arrastra y suelta tu archivo aquí, o haz clic para navegar",
    "health.images.supportedFormats": "Formatos soportados: PDF, JPG, PNG, DICOM",
    "health.images.xray": "Rayos X",
    "health.images.ultrasound": "Ultrasonido",
    "health.images.mri": "Resonancia Magnética",
    "health.images.ctScan": "Tomografía",
    "health.images.others": "Otros",
    "health.images.noFindings": "Sin Hallazgos",
    "health.images.lowRiskFindings": "Hallazgos de Bajo Riesgo",
    "health.images.relevantFindings": "Hallazgos Relevantes",
    "health.images.noImagesInCategory": "Aún no hay imágenes en esta categoría",
    "health.images.view": "Ver",
    "health.images.reportConclusions": "Conclusiones del Informe",
    "health.images.medicalConclusions": "Conclusiones Médicas",
    "health.images.viewFullReport": "Ver Informe Completo",

    "tabs.profile": "Perfil",
    "tabs.emergency": "Emergencia",
    "tabs.insurance": "Seguro",
    "tabs.security": "Seguridad",
    "tabs.notifications": "Notificaciones",
    "tabs.integrations": "Integraciones",
    "tabs.preferences": "Preferencias",
    "tabs.privacy": "Privacidad",

    "profile.fullName": "Nombre Completo",
    "profile.email": "Correo Electrónico",
    "profile.phone": "Teléfono",
    "profile.dob": "Fecha de Nacimiento",
    "profile.height": "Altura",
    "profile.weight": "Peso",
    "profile.address": "Dirección",
    "profile.medicalNotes": "Notas Médicas",
    "profile.medicalNotesDesc": "Esta información será compartida con tus proveedores de atención médica",
    "profile.updateProfile": "Actualizar Perfil",
    "profile.manageProfile": "Gestiona tu perfil y configuraciones de la aplicación",

    "emergency.contacts": "Contactos de Emergencia",
    "emergency.primaryContact": "Contacto Primario",
    "emergency.secondaryContact": "Contacto Secundario",
    "emergency.phoneNumber": "Número de Teléfono",
    "emergency.medicalInfo": "Información Médica",
    "emergency.bloodType": "Tipo de Sangre",
    "emergency.allergies": "Alergias",
    "emergency.medicalConditions": "Condiciones Médicas",
    "emergency.saveInfo": "Guardar Información",

    "insurance.primary": "Seguro Primario",
    "insurance.secondary": "Seguro Secundario",
    "insurance.provider": "Proveedor de Seguros",
    "insurance.policyNumber": "Número de Póliza",
    "insurance.groupNumber": "Número de Grupo",
    "insurance.memberId": "ID de Miembro",
    "insurance.addInsurance": "Añadir Seguro",
    "insurance.uploadCard": "Subir Tarjeta",
    "insurance.saveInfo": "Guardar Información",

    "security.password": "Contraseña",
    "security.currentPassword": "Contraseña Actual",
    "security.newPassword": "Nueva Contraseña",
    "security.confirmPassword": "Confirmar Contraseña",
    "security.twoFactor": "Autenticación de Dos Factores",
    "security.authenticatorApp": "Aplicación de Autenticación",
    "security.authenticatorDesc":
      "Usa una aplicación de autenticación para generar contraseñas de un solo uso basadas en tiempo",
    "security.loginSessions": "Sesiones de Inicio de Sesión",
    "security.currentSession": "Sesión Actual",
    "security.previousSession": "Sesión Anterior",
    "security.saveSettings": "Guardar Configuraciones",

    "notifications.email": "Notificaciones por Correo",
    "notifications.emailDesc": "Recibir recordatorios de citas por correo electrónico",
    "notifications.medicationDesc": "Recibir recordatorios de medicamentos por correo electrónico",
    "notifications.resultsDesc": "Recibir resultados de pruebas por correo electrónico",
    "notifications.newsletterDesc": "Recibir boletín mensual y consejos de salud",
    "notifications.sms": "Notificaciones SMS",
    "notifications.smsAppointmentDesc": "Recibir recordatorios de citas por SMS",
    "notifications.smsMedicationDesc": "Recibir recordatorios de medicamentos por SMS",
    "notifications.smsResultsDesc": "Recibir resultados de pruebas por SMS",
    "notifications.push": "Notificaciones Push",
    "notifications.pushAppointmentDesc": "Recibir recordatorios de citas por notificaciones push",
    "notifications.pushMedicationDesc": "Recibir recordatorios de medicamentos por notificaciones push",
    "notifications.pushResultsDesc": "Recibir resultados de pruebas por notificaciones push",
    "notifications.appointmentReminders": "Recordatorios de Citas",
    "notifications.medicationReminders": "Recordatorios de Medicamentos",
    "notifications.testResults": "Resultados de Pruebas",
    "notifications.newsletter": "Boletín",
    "notifications.savePreferences": "Guardar Preferencias",

    "integrations.healthFitness": "Integraciones de Salud y Fitness",
    "integrations.syncDesc": "Sincroniza tus datos de salud desde estos servicios",
    "integrations.newIntegration": "Nueva Integración",
    "integrations.addNew": "Añadir Nueva Integración",
    "integrations.connectDesc": "Conecta tu cuenta para sincronizar datos de salud",
    "integrations.partner": "Socio de Integración",
    "integrations.appleHealth": "Apple Health",
    "integrations.appleHealthDesc": "Sincronizar datos desde Apple Health",
    "integrations.googleFit": "Google Fit",
    "integrations.googleFitDesc": "Sincronizar datos desde Google Fit",
    "integrations.withings": "Withings",
    "integrations.withingsDesc": "Sincronizar datos desde dispositivos Withings",
    "integrations.fitbit": "Fitbit",
    "integrations.fitbitDesc": "Sincronizar datos desde dispositivos Fitbit",
    "integrations.garmin": "Garmin",
    "integrations.garminDesc": "Sincronizar datos desde dispositivos Garmin",
    "integrations.ouraRing": "Oura Ring",
    "integrations.ouraRingDesc": "Sincronizar datos desde Oura Ring",
    "integrations.saveSettings": "Guardar Configuraciones",

    "preferences.theme": "Tema",
    "preferences.light": "Claro",
    "preferences.dark": "Oscuro",
    "preferences.system": "Sistema",
    "preferences.accessibility": "Accesibilidad",
    "preferences.textSize": "Tamaño de Texto",
    "preferences.reduceMotion": "Reducir Movimiento",
    "preferences.reduceMotionDesc": "Minimizar animaciones en toda la aplicación",
    "preferences.highContrast": "Alto Contraste",
    "preferences.highContrastDesc": "Aumentar contraste para mejor legibilidad",
    "preferences.language": "Idioma",
    "preferences.timezone": "Zona Horaria",
    "preferences.units": "Unidades",
    "preferences.imperial": "Imperial (lbs, in, F)",
    "preferences.metric": "Métrico (kg, cm, C)",
    "preferences.savePreferences": "Guardar Preferencias",
    "preferences.savedSuccessfully": "¡Preferencias guardadas exitosamente!",
    "preferences.savedSuccessfullyDesc": "Tus preferencias han sido actualizadas.",

    "privacy.settings": "Configuraciones de Privacidad",
    "privacy.dataSharing": "Compartir Datos",
    "privacy.dataSharingDesc": "Compartir datos anonimizados para mejorar servicios de salud",
    "privacy.research": "Participación en Investigación",
    "privacy.researchDesc": "Participar en estudios de investigación de salud",
    "privacy.analytics": "Analíticas",
    "privacy.analyticsDesc": "Permitir analíticas de uso para mejorar la aplicación",
    "privacy.saveSettings": "Guardar Configuraciones",
    "privacy.dataManagement": "Gestión de Datos",
    "privacy.requestData": "Solicitar Exportación de Datos",
    "privacy.dataRequest": "Solicitud de Datos",
    "privacy.dataRequestDesc": "Solicita una copia de tus datos o eliminación de tu cuenta",
    "privacy.requestType": "Tipo de Solicitud",
    "privacy.dataExport": "Exportación de Datos",
    "privacy.dataDeletion": "Eliminación de Datos",
    "privacy.accountDeletion": "Eliminación de Cuenta",
    "privacy.reason": "Razón de la Solicitud",
    "privacy.reasonPlaceholder": "Por favor proporciona una razón para tu solicitud",
    "privacy.emailDownload": "Correo para Enlace de Descarga",
    "privacy.emailDownloadDesc": "Te enviaremos un enlace de descarga seguro a este correo",

    "notifications.title": "Notificaciones",
    "notifications.markAllAsRead": "Marcar todo como leído",
    "notifications.noNotifications": "No hay nuevas notificaciones",
    "notifications.new_message_title": "Nuevo mensaje",
    "notifications.new_message_description": "Has recibido un nuevo mensaje de tu médico",
    "notifications.appointment_reminder_title": "Recordatorio de cita",
    "notifications.appointment_reminder_description": "Tienes una cita mañana a las 10:00 AM",
    "notifications.medication_reminder_title": "Recordatorio de medicación",
    "notifications.medication_reminder_description": "Es hora de tomar tu medicación",

    // Health Records
    "health.condition": "Condición",
    "health.statusLabel": "Estado",
    "health.notes": "Notas",
    "health.resolvedDate": "Fecha de Resolución",
    "health.editCurrentConditions": "Editar Condiciones Médicas Actuales",
    "health.editCurrentConditionsDesc": "Gestiona tus condiciones médicas actuales y su estado",
    "health.editPastConditions": "Editar Condiciones Médicas Pasadas",
    "health.editPastConditionsDesc": "Gestiona tus condiciones médicas pasadas que han sido resueltas",
    "health.editFamilyHistory": "Editar Historial Médico Familiar",
    "health.editFamilyHistoryDesc": "Gestiona tu historial médico familiar",
    "health.status.controlled": "Controlado",
    "health.status.partiallyControlled": "Parcialmente Controlado",
    "health.status.uncontrolled": "No Controlado",
  },
  pt: {
    // Navigation
    "nav.dashboard": "Painel",
    "nav.healthRecords": "Registos de Saúde",
    "nav.healthPlan": "Plano de Saúde",
    "nav.medications": "Medicamentos",
    "nav.messages": "Mensagens",
    "nav.appointments": "Consultas",
    "nav.permissions": "Permissões",
    "nav.profileSettings": "Perfil e Configurações",
    "nav.logout": "Terminar Sessão",
    "nav.healthGoals": "Metas de Saúde",

    // Common actions
    "action.save": "Guardar",
    "action.cancel": "Cancelar",
    "action.add": "Adicionar",
    "action.edit": "Editar",
    "action.delete": "Eliminar",
    "action.update": "Atualizar",
    "action.connect": "Ligar",
    "action.revoke": "Revogar",
    "action.current": "Atual",
    "action.submit": "Submeter",
    "action.download": "Descarregar",

    // Greetings
    "greeting.morning": "Bom dia",
    "greeting.afternoon": "Boa tarde",
    "greeting.evening": "Boa noite",

    // Health Records
    "health.controlRecords": "Controle os seus registos de saúde e bem-estar para melhorar a sua condição!",
    "health.summary": "Resumo",
    "health.history": "Histórico",
    "health.analysis": "Análise",
    "health.body": "Corpo",
    "health.lifestyle": "Estilo de Vida",
    "health.vitals": "Sinais Vitais",
    "health.genetics": "Genética",
    "health.images": "Exames",

    // Health Images
    "health.images.medicalImages": "Imagens Médicas",
    "health.images.aiSummary": "Resumo IA",
    "health.images.aiSummaryContent":
      "Com base nos seus estudos de imagem recentes, a maioria dos achados está dentro dos limites normais. A sua radiografia torácica não mostra anormalidades agudas, e a ressonância magnética cerebral é normal. No entanto, deve ser dada atenção aos pequenos nódulos pulmonares encontrados na tomografia computorizada - recomenda-se seguimento com imagens em 3 meses. As alterações degenerativas ligeiras na sua coluna vertebral e joelho são apropriadas para a idade, mas podem beneficiar de fisioterapia se os sintomas persistirem.",
    "health.images.uploadImage": "Carregar Imagem",
    "health.images.uploadNewImage": "Carregar Nova Imagem Médica",
    "health.images.uploadDescription": "Carregue um relatório de imagem médica e forneça os detalhes necessários.",
    "health.images.imageType": "Tipo de Imagem",
    "health.images.selectImageType": "Selecionar tipo de imagem",
    "health.images.bodyPart": "Parte do Corpo",
    "health.images.bodyPartPlaceholder": "ex., Tórax, Joelho Esquerdo, Cérebro",
    "health.images.imageDate": "Data da Imagem",
    "health.images.findings": "Achados",
    "health.images.selectFindings": "Selecionar achados",
    "health.images.conclusions": "Conclusões",
    "health.images.conclusionsPlaceholder": "Introduza as conclusões médicas do relatório",
    "health.images.uploadFile": "Carregar Ficheiro",
    "health.images.dragDropOrClick": "Arraste e solte o seu ficheiro aqui, ou clique para navegar",
    "health.images.supportedFormats": "Formatos suportados: PDF, JPG, PNG, DICOM",
    "health.images.xray": "Raios-X",
    "health.images.ultrasound": "Ultrassom",
    "health.images.mri": "Ressonância Magnética",
    "health.images.ctScan": "Tomografia",
    "health.images.others": "Outros",
    "health.images.noFindings": "Sem Achados",
    "health.images.lowRiskFindings": "Achados de Baixo Risco",
    "health.images.relevantFindings": "Achados Relevantes",
    "health.images.noImagesInCategory": "Ainda não há imagens nesta categoria",
    "health.images.view": "Ver",
    "health.images.reportConclusions": "Conclusões do Relatório",
    "health.images.medicalConclusions": "Conclusões Médicas",
    "health.images.viewFullReport": "Ver Relatório Completo",

    "tabs.profile": "Perfil",
    "tabs.emergency": "Emergência",
    "tabs.insurance": "Seguro",
    "tabs.security": "Segurança",
    "tabs.notifications": "Notificações",
    "tabs.integrations": "Integrações",
    "tabs.preferences": "Preferências",
    "tabs.privacy": "Privacidade",

    "profile.fullName": "Nome Completo",
    "profile.email": "Email",
    "profile.phone": "Telefone",
    "profile.dob": "Data de Nascimento",
    "profile.height": "Altura",
    "profile.weight": "Peso",
    "profile.address": "Morada",
    "profile.medicalNotes": "Notas Médicas",
    "profile.medicalNotesDesc": "Esta informação será partilhada com os seus prestadores de cuidados de saúde",
    "profile.updateProfile": "Atualizar Perfil",
    "profile.manageProfile": "Gerir o seu perfil e configurações da aplicação",

    "emergency.contacts": "Contactos de Emergência",
    "emergency.primaryContact": "Contacto Primário",
    "emergency.secondaryContact": "Contacto Secundário",
    "emergency.phoneNumber": "Número de Telefone",
    "emergency.medicalInfo": "Informação Médica",
    "emergency.bloodType": "Tipo Sanguíneo",
    "emergency.allergies": "Alergias",
    "emergency.medicalConditions": "Condições Médicas",
    "emergency.saveInfo": "Guardar Informação",

    "insurance.primary": "Seguro Primário",
    "insurance.secondary": "Seguro Secundário",
    "insurance.provider": "Seguradora",
    "insurance.policyNumber": "Número da Apólice",
    "insurance.groupNumber": "Número do Grupo",
    "insurance.memberId": "ID de Membro",
    "insurance.addInsurance": "Adicionar Seguro",
    "insurance.uploadCard": "Carregar Cartão",
    "insurance.saveInfo": "Guardar Informação",

    "security.password": "Palavra-passe",
    "security.currentPassword": "Palavra-passe Atual",
    "security.newPassword": "Nova Palavra-passe",
    "security.confirmPassword": "Confirmar Palavra-passe",
    "security.twoFactor": "Autenticação de Dois Fatores",
    "security.authenticatorApp": "Aplicação de Autenticação",
    "security.authenticatorDesc":
      "Use uma aplicação de autenticação para gerar palavras-passe únicas baseadas em tempo",
    "security.loginSessions": "Sessões de Login",
    "security.currentSession": "Sessão Atual",
    "security.previousSession": "Sessão Anterior",
    "security.saveSettings": "Guardar Configurações",

    "notifications.email": "Notificações por Email",
    "notifications.emailDesc": "Receber lembretes de consultas por email",
    "notifications.medicationDesc": "Receber lembretes de medicação por email",
    "notifications.resultsDesc": "Receber resultados de testes por email",
    "notifications.newsletterDesc": "Receber newsletter mensal e dicas de saúde",
    "notifications.sms": "Notificações SMS",
    "notifications.smsAppointmentDesc": "Receber lembretes de consultas por SMS",
    "notifications.smsMedicationDesc": "Receber lembretes de medicação por SMS",
    "notifications.smsResultsDesc": "Receber resultados de testes por SMS",
    "notifications.push": "Notificações Push",
    "notifications.pushAppointmentDesc": "Receber lembretes de consultas por notificações push",
    "notifications.pushMedicationDesc": "Receber lembretes de medicação por notificações push",
    "notifications.pushResultsDesc": "Receber resultados de testes por notificações push",
    "notifications.appointmentReminders": "Lembretes de Consultas",
    "notifications.medicationReminders": "Lembretes de Medicação",
    "notifications.testResults": "Resultados de Testes",
    "notifications.newsletter": "Newsletter",
    "notifications.savePreferences": "Guardar Preferências",

    "integrations.healthFitness": "Integrações de Saúde e Fitness",
    "integrations.syncDesc": "Sincronize os seus dados de saúde destes serviços",
    "integrations.newIntegration": "Nova Integração",
    "integrations.addNew": "Adicionar Nova Integração",
    "integrations.connectDesc": "Ligue a sua conta para sincronizar dados de saúde",
    "integrations.partner": "Parceiro de Integração",
    "integrations.appleHealth": "Apple Health",
    "integrations.appleHealthDesc": "Sincronizar dados do Apple Health",
    "integrations.googleFit": "Google Fit",
    "integrations.googleFitDesc": "Sincronizar dados do Google Fit",
    "integrations.withings": "Withings",
    "integrations.withingsDesc": "Sincronizar dados de dispositivos Withings",
    "integrations.fitbit": "Fitbit",
    "integrations.fitbitDesc": "Sincronizar dados de dispositivos Fitbit",
    "integrations.garmin": "Garmin",
    "integrations.garminDesc": "Sincronizar dados de dispositivos Garmin",
    "integrations.ouraRing": "Oura Ring",
    "integrations.ouraRingDesc": "Sincronizar dados do Oura Ring",
    "integrations.saveSettings": "Guardar Configurações",

    "preferences.theme": "Tema",
    "preferences.light": "Claro",
    "preferences.dark": "Escuro",
    "preferences.system": "Sistema",
    "preferences.accessibility": "Acessibilidade",
    "preferences.textSize": "Tamanho do Texto",
    "preferences.reduceMotion": "Reduzir Movimento",
    "preferences.reduceMotionDesc": "Minimizar animações em toda a aplicação",
    "preferences.highContrast": "Alto Contraste",
    "preferences.highContrastDesc": "Aumentar contraste para melhor legibilidade",
    "preferences.language": "Idioma",
    "preferences.timezone": "Fuso Horário",
    "preferences.units": "Unidades",
    "preferences.imperial": "Imperial (lbs, in, F)",
    "preferences.metric": "Métrico (kg, cm, C)",
    "preferences.savePreferences": "Guardar Preferências",
    "preferences.savedSuccessfully": "Preferências guardadas com sucesso!",
    "preferences.savedSuccessfullyDesc": "As suas preferências foram atualizadas.",

    "privacy.settings": "Configurações de Privacidade",
    "privacy.dataSharing": "Partilha de Dados",
    "privacy.dataSharingDesc": "Partilhar dados anonimizados para melhorar serviços de saúde",
    "privacy.research": "Participação em Investigação",
    "privacy.researchDesc": "Participar em estudos de investigação de saúde",
    "privacy.analytics": "Análises",
    "privacy.analyticsDesc": "Permitir análises de uso para melhorar a aplicação",
    "privacy.saveSettings": "Guardar Configurações",
    "privacy.dataManagement": "Gestão de Dados",
    "privacy.requestData": "Solicitar Exportação de Dados",
    "privacy.dataRequest": "Solicitação de Dados",
    "privacy.dataRequestDesc": "Solicite uma cópia dos seus dados ou eliminação da sua conta",
    "privacy.requestType": "Tipo de Solicitação",
    "privacy.dataExport": "Exportação de Dados",
    "privacy.dataDeletion": "Eliminação de Dados",
    "privacy.accountDeletion": "Eliminação de Conta",
    "privacy.reason": "Razão da Solicitação",
    "privacy.reasonPlaceholder": "Por favor forneça uma razão para a sua solicitação",
    "privacy.emailDownload": "Email para Link de Download",
    "privacy.emailDownloadDesc": "Enviaremos um link de download seguro para este email",

    "notifications.title": "Notificações",
    "notifications.markAllAsRead": "Marcar tudo como lido",
    "notifications.noNotifications": "Sem novas notificações",
    "notifications.new_message_title": "Nova mensagem",
    "notifications.new_message_description": "Recebeu uma nova mensagem do seu médico",
    "notifications.appointment_reminder_title": "Lembrete de consulta",
    "notifications.appointment_reminder_description": "Tem uma consulta amanhã às 10:00",
    "notifications.medication_reminder_title": "Lembrete de medicação",
    "notifications.medication_reminder_description": "Hora de tomar a sua medicação",

    // Health Records
    "health.condition": "Condição",
    "health.statusLabel": "Estado",
    "health.notes": "Notas",
    "health.resolvedDate": "Data de Resolução",
    "health.editCurrentConditions": "Editar Condições Médicas Atuais",
    "health.editCurrentConditionsDesc": "Gerir as suas condições médicas atuais e o seu estado",
    "health.editPastConditions": "Editar Condições Médicas Passadas",
    "health.editPastConditionsDesc": "Gerir as suas condições médicas passadas que foram resolvidas",
    "health.editFamilyHistory": "Editar Historial Médico Familiar",
    "health.editFamilyHistoryDesc": "Gerir o seu historial médico familiar",
    "health.status.controlled": "Controlado",
    "health.status.partiallyControlled": "Parcialmente Controlado",
    "health.status.uncontrolled": "Não Controlado",
  },
}

// Create the provider component
export function LanguageProvider({ children }: { children: ReactNode }) {
  // Try to get the saved language from localStorage, default to English
  const [language, setLanguage] = useState<Language>("en")

  // Load saved language on initial render
  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && ["en", "es", "pt"].includes(savedLanguage)) {
      setLanguage(savedLanguage)
    }
  }, [])

  // Save language to localStorage when it changes
  useEffect(() => {
    localStorage.setItem("language", language)
  }, [language])

  // Translation function
  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

// Custom hook to use the language context
export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
