// Sample appointments data
export const appointments = [
  {
    id: "1",
    doctor: "Dr. Sarah Johnson",
    specialty: "Cardiologist",
    date: "2023-05-20T10:00:00",
    status: "upcoming",
    type: "virtual",
  },
  {
    id: "2",
    doctor: "Dr. Michael Chen",
    specialty: "Primary Care",
    date: "2023-05-25T14:30:00",
    status: "upcoming",
    type: "in-person",
  },
  {
    id: "3",
    doctor: "Dr. Emily Rodriguez",
    specialty: "Endocrinologist",
    date: "2023-04-15T11:00:00",
    status: "completed",
    type: "in-person",
  },
  {
    id: "4",
    doctor: "Dr. James Wilson",
    specialty: "Dermatologist",
    date: "2023-04-10T09:30:00",
    status: "cancelled",
    type: "virtual",
  },
  {
    id: "5",
    doctor: "Dr. Lisa Patel",
    specialty: "Psychiatrist",
    date: "2023-05-30T13:00:00",
    status: "upcoming",
    type: "phone",
  },
]

export const medications = {
  current: [
    {
      id: "med1",
      name: "Lisinopril",
      dosage: "10mg",
      frequency: "Once daily",
      purpose: "Blood pressure management",
      prescribedBy: "Dr. Sarah Johnson",
      startDate: "January 15, 2023",
      refillDate: "July 15, 2023",
      instructions: "Take one tablet by mouth once daily in the morning with or without food.",
      reminders: [
        {
          id: "rem1",
          time: "08:00",
          days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
          enabled: true,
        },
      ],
      prescription: {
        number: "RX12345678",
        pharmacy: "MediCare Pharmacy",
        originalQuantity: "90 tablets",
        refillsRemaining: "2",
        lastFilled: "April 15, 2023",
        datePrescribed: "January 15, 2023",
        refillsAuthorized: "3",
        prescriber: "Dr. Sarah Johnson",
      },
    },
    {
      id: "med2",
      name: "Atorvastatin",
      dosage: "20mg",
      frequency: "Once daily",
      purpose: "Cholesterol management",
      prescribedBy: "Dr. Sarah Johnson",
      startDate: "January 15, 2023",
      refillDate: "July 15, 2023",
      instructions: "Take one tablet by mouth once daily in the evening.",
      reminders: [
        {
          id: "rem2",
          time: "20:00",
          days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
          enabled: true,
        },
      ],
      prescription: {
        number: "RX12345679",
        pharmacy: "MediCare Pharmacy",
        originalQuantity: "90 tablets",
        refillsRemaining: "2",
        lastFilled: "April 15, 2023",
        datePrescribed: "January 15, 2023",
        refillsAuthorized: "3",
        prescriber: "Dr. Sarah Johnson",
      },
    },
    {
      id: "med3",
      name: "Metformin",
      dosage: "500mg",
      frequency: "Twice daily",
      purpose: "Diabetes management",
      prescribedBy: "Dr. Michael Chen",
      startDate: "February 10, 2023",
      refillDate: "August 10, 2023",
      instructions: "Take one tablet by mouth twice daily with meals.",
      reminders: [
        {
          id: "rem3a",
          time: "08:00",
          days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
          enabled: true,
        },
        {
          id: "rem3b",
          time: "18:00",
          days: ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"],
          enabled: true,
        },
      ],
      prescription: {
        number: "RX12345680",
        pharmacy: "MediCare Pharmacy",
        originalQuantity: "180 tablets",
        refillsRemaining: "3",
        lastFilled: "May 10, 2023",
        datePrescribed: "February 10, 2023",
        refillsAuthorized: "5",
        prescriber: "Dr. Michael Chen",
      },
    },
  ],
  previous: [
    {
      id: "med4",
      name: "Amoxicillin",
      dosage: "500mg",
      frequency: "Three times daily",
      purpose: "Bacterial infection",
      prescribedBy: "Dr. Emily Rodriguez",
      startDate: "November 5, 2022",
      endDate: "November 15, 2022",
      reason: "Course completed",
      prescription: {
        number: "RX12345681",
        pharmacy: "MediCare Pharmacy",
        originalQuantity: "30 tablets",
        lastFilled: "November 5, 2022",
        datePrescribed: "November 5, 2022",
        refillsAuthorized: "0",
        prescriber: "Dr. Emily Rodriguez",
      },
    },
    {
      id: "med5",
      name: "Prednisone",
      dosage: "10mg",
      frequency: "Once daily",
      purpose: "Inflammation",
      prescribedBy: "Dr. James Wilson",
      startDate: "October 10, 2022",
      endDate: "October 24, 2022",
      reason: "Course completed",
      prescription: {
        number: "RX12345682",
        pharmacy: "MediCare Pharmacy",
        originalQuantity: "14 tablets",
        lastFilled: "October 10, 2022",
        datePrescribed: "October 10, 2022",
        refillsAuthorized: "0",
        prescriber: "Dr. James Wilson",
      },
    },
  ],
}

export const healthMetrics = {
  bloodPressure: [
    { date: "2023-01-15", systolic: 145, diastolic: 92 },
    { date: "2023-02-15", systolic: 142, diastolic: 90 },
    { date: "2023-03-15", systolic: 138, diastolic: 88 },
    { date: "2023-04-15", systolic: 135, diastolic: 87 },
    { date: "2023-05-15", systolic: 132, diastolic: 85 },
  ],
  weight: [
    { date: "2023-01-15", value: 165 },
    { date: "2023-02-15", value: 163 },
    { date: "2023-03-15", value: 161 },
    { date: "2023-04-15", value: 160 },
    { date: "2023-05-15", value: 158 },
  ],
  glucose: [
    { date: "2023-01-15", value: 110 },
    { date: "2023-02-15", value: 108 },
    { date: "2023-03-15", value: 105 },
    { date: "2023-04-15", value: 102 },
    { date: "2023-05-15", value: 98 },
  ],
  cholesterol: [
    { date: "2023-01-15", total: 210, ldl: 135, hdl: 46, triglycerides: 145 },
    { date: "2023-03-15", total: 200, ldl: 130, hdl: 48, triglycerides: 140 },
    { date: "2023-05-15", total: 195, ldl: 125, hdl: 50, triglycerides: 135 },
  ],
  bodyComposition: {
    bodyFat: [
      { date: "2023-01-15", value: 26.3 },
      { date: "2023-02-15", value: 25.8 },
      { date: "2023-03-15", value: 25.2 },
      { date: "2023-04-15", value: 24.7 },
      { date: "2023-05-15", value: 24.0 },
    ],
    muscleMass: [
      { date: "2023-01-15", value: 30.5 },
      { date: "2023-02-15", value: 30.9 },
      { date: "2023-03-15", value: 31.2 },
      { date: "2023-04-15", value: 31.6 },
      { date: "2023-05-15", value: 32.0 },
    ],
    waist: [
      { date: "2023-01-15", value: 34 },
      { date: "2023-02-15", value: 33.5 },
      { date: "2023-03-15", value: 33 },
      { date: "2023-04-15", value: 32.5 },
      { date: "2023-05-15", value: 32 },
    ],
  },
  lifestyle: {
    aiSummary:
      "Your lifestyle metrics indicate good sleep quality but insufficient daily activity. Your average of 6,200 steps is below the recommended 10,000 steps per day. Consider increasing your daily walks and structured exercise sessions to improve cardiovascular health and support your weight management goals.",
    sleep: [
      { date: "2023-05-10", hours: 7.1, deepSleep: 2.5, quality: "Good" },
      { date: "2023-05-11", hours: 6.8, deepSleep: 2.3, quality: "Fair" },
      { date: "2023-05-12", hours: 7.5, deepSleep: 2.8, quality: "Good" },
      { date: "2023-05-13", hours: 7.2, deepSleep: 2.6, quality: "Good" },
      { date: "2023-05-14", hours: 7.0, deepSleep: 2.4, quality: "Good" },
      { date: "2023-05-15", hours: 7.6, deepSleep: 3.0, quality: "Excellent" },
      { date: "2023-05-16", hours: 7.2, deepSleep: 2.7, quality: "Good" },
    ],
    steps: [
      { date: "2023-05-10", count: 5200 },
      { date: "2023-05-11", count: 5800 },
      { date: "2023-05-12", count: 6500 },
      { date: "2023-05-13", count: 7200 },
      { date: "2023-05-14", count: 4800 },
      { date: "2023-05-15", count: 6900 },
      { date: "2023-05-16", count: 6200 },
    ],
    workouts: [
      { date: "2023-05-01", type: "Cardio", duration: 30, calories: 250 },
      { date: "2023-05-03", type: "Strength", duration: 45, calories: 320 },
      { date: "2023-05-05", type: "Cardio", duration: 35, calories: 280 },
      { date: "2023-05-08", type: "Strength", duration: 40, calories: 300 },
      { date: "2023-05-10", type: "Cardio", duration: 30, calories: 245 },
      { date: "2023-05-12", type: "Strength", duration: 50, calories: 350 },
    ],
  },
  vitals: {
    aiSummary:
      "Your vital signs are generally within normal ranges, though your blood pressure remains slightly elevated. Your heart rate variability has improved, suggesting better cardiovascular fitness. Continue monitoring your blood pressure daily and maintain your medication regimen.",
    heartRate: [
      { date: "2023-05-10", resting: 72, max: 145 },
      { date: "2023-05-11", resting: 70, max: 150 },
      { date: "2023-05-12", resting: 71, max: 148 },
      { date: "2023-05-13", resting: 69, max: 152 },
      { date: "2023-05-14", resting: 67, max: 146 },
      { date: "2023-05-15", resting: 68, max: 149 },
      { date: "2023-05-16", resting: 68, max: 147 },
    ],
    oxygenSaturation: [
      { date: "2023-05-10", value: 97 },
      { date: "2023-05-11", value: 97 },
      { date: "2023-05-12", value: 98 },
      { date: "2023-05-13", value: 98 },
      { date: "2023-05-14", value: 97 },
      { date: "2023-05-15", value: 98 },
      { date: "2023-05-16", value: 98 },
    ],
    ecgResults: [
      {
        date: "2023-04-10",
        result: "Normal sinus rhythm",
        doctor: "Dr. Michael Chen",
        fileUrl: "/documents/ecg-20230410.pdf",
        notes: "No abnormalities detected. Regular rhythm with normal P waves, QRS complexes, and T waves.",
      },
      {
        date: "2023-01-15",
        result: "Normal sinus rhythm",
        doctor: "Dr. Michael Chen",
        fileUrl: "/documents/ecg-20230115.pdf",
        notes: "No abnormalities detected. Regular rhythm with normal P waves, QRS complexes, and T waves.",
      },
    ],
    heartSounds: [
      {
        date: "2023-04-10",
        result: "Normal S1 and S2, no murmurs",
        doctor: "Dr. Michael Chen",
        fileUrl: "/documents/heart-sounds-20230410.mp3",
        notes: "Normal heart sounds with regular S1 and S2. No murmurs, gallops, or rubs detected.",
      },
    ],
  },
  bloodTests: {
    aiSummary:
      "Your blood test results show improvement in cholesterol levels, though LDL remains slightly elevated. Your glucose levels have normalized, indicating good response to your current treatment plan. Continue with your medication regimen and dietary modifications to further improve lipid profile.",
    complete: [
      {
        date: "2023-04-15",
        components: [
          { name: "White Blood Cells", value: 11.2, unit: "K/uL", status: "abnormal", normal: "4.5-10.0" },
          { name: "Red Blood Cells", value: 4.8, unit: "M/uL", status: "normal", normal: "4.5-5.5" },
          { name: "Hemoglobin", value: 14.2, unit: "g/dL", status: "normal", normal: "13.5-17.5" },
          { name: "Hematocrit", value: 42, unit: "%", status: "normal", normal: "41-50" },
          { name: "Platelets", value: 250, unit: "K/uL", status: "normal", normal: "150-450" },
        ],
      },
      {
        date: "2023-01-15",
        components: [
          { name: "White Blood Cells", value: 12.0, unit: "K/uL", status: "abnormal", normal: "4.5-10.0" },
          { name: "Red Blood Cells", value: 4.7, unit: "M/uL", status: "normal", normal: "4.5-5.5" },
          { name: "Hemoglobin", value: 14.0, unit: "g/dL", status: "normal", normal: "13.5-17.5" },
          { name: "Hematocrit", value: 41, unit: "%", status: "normal", normal: "41-50" },
          { name: "Platelets", value: 245, unit: "K/uL", status: "normal", normal: "150-450" },
        ],
      },
    ],
    metabolic: [
      {
        date: "2023-04-15",
        components: [
          { name: "Glucose", value: 98, unit: "mg/dL", status: "normal", normal: "70-99" },
          { name: "BUN", value: 15, unit: "mg/dL", status: "normal", normal: "7-20" },
          { name: "Creatinine", value: 0.9, unit: "mg/dL", status: "normal", normal: "0.6-1.2" },
          { name: "Sodium", value: 140, unit: "mmol/L", status: "normal", normal: "136-145" },
          { name: "Potassium", value: 4.0, unit: "mmol/L", status: "normal", normal: "3.5-5.1" },
          { name: "Calcium", value: 9.5, unit: "mg/dL", status: "normal", normal: "8.5-10.2" },
        ],
      },
      {
        date: "2023-01-15",
        components: [
          { name: "Glucose", value: 110, unit: "mg/dL", status: "abnormal", normal: "70-99" },
          { name: "BUN", value: 16, unit: "mg/dL", status: "normal", normal: "7-20" },
          { name: "Creatinine", value: 0.9, unit: "mg/dL", status: "normal", normal: "0.6-1.2" },
          { name: "Sodium", value: 139, unit: "mmol/L", status: "normal", normal: "136-145" },
          { name: "Potassium", value: 3.9, unit: "mmol/L", status: "normal", normal: "3.5-5.1" },
          { name: "Calcium", value: 9.4, unit: "mg/dL", status: "normal", normal: "8.5-10.2" },
        ],
      },
    ],
    lipid: [
      {
        date: "2023-04-15",
        components: [
          { name: "Total Cholesterol", value: 195, unit: "mg/dL", status: "normal", normal: "<200" },
          { name: "LDL Cholesterol", value: 125, unit: "mg/dL", status: "abnormal", normal: "<100" },
          { name: "HDL Cholesterol", value: 50, unit: "mg/dL", status: "normal", normal: ">40" },
          { name: "Triglycerides", value: 135, unit: "mg/dL", status: "normal", normal: "<150" },
        ],
      },
      {
        date: "2023-01-15",
        components: [
          { name: "Total Cholesterol", value: 210, unit: "mg/dL", status: "abnormal", normal: "<200" },
          { name: "LDL Cholesterol", value: 135, unit: "mg/dL", status: "abnormal", normal: "<100" },
          { name: "HDL Cholesterol", value: 46, unit: "mg/dL", status: "normal", normal: ">40" },
          { name: "Triglycerides", value: 145, unit: "mg/dL", status: "normal", normal: "<150" },
        ],
      },
    ],
    bloodGlucose: [
      {
        date: "2023-05-15",
        value: 98,
        unit: "mg/dL",
        status: "normal",
        normal: "70-99",
        trend: "improving",
        change: "-12",
      },
      {
        date: "2023-04-15",
        value: 102,
        unit: "mg/dL",
        status: "abnormal",
        normal: "70-99",
        trend: "improving",
        change: "-3",
      },
      {
        date: "2023-03-15",
        value: 105,
        unit: "mg/dL",
        status: "abnormal",
        normal: "70-99",
        trend: "improving",
        change: "-3",
      },
      {
        date: "2023-02-15",
        value: 108,
        unit: "mg/dL",
        status: "abnormal",
        normal: "70-99",
        trend: "improving",
        change: "-2",
      },
      {
        date: "2023-01-15",
        value: 110,
        unit: "mg/dL",
        status: "abnormal",
        normal: "70-99",
        trend: "stable",
        change: "0",
      },
    ],
    bloodParameters: [
      {
        name: "Glucose",
        current: "98 mg/dL",
        status: "normal",
        change: "-12 mg/dL",
        normal: "70-99 mg/dL",
        trend: "improving",
      },
      {
        name: "Total Cholesterol",
        current: "195 mg/dL",
        status: "normal",
        change: "-15 mg/dL",
        normal: "<200 mg/dL",
        trend: "improving",
      },
      {
        name: "LDL Cholesterol",
        current: "125 mg/dL",
        status: "abnormal",
        change: "-10 mg/dL",
        normal: "<100 mg/dL",
        trend: "improving",
      },
      {
        name: "HDL Cholesterol",
        current: "50 mg/dL",
        status: "normal",
        change: "+4 mg/dL",
        normal: ">40 mg/dL",
        trend: "improving",
      },
      {
        name: "Triglycerides",
        current: "135 mg/dL",
        status: "normal",
        change: "-10 mg/dL",
        normal: "<150 mg/dL",
        trend: "improving",
      },
      {
        name: "White Blood Cells",
        current: "11.2 K/uL",
        status: "abnormal",
        change: "-0.8 K/uL",
        normal: "4.5-10.0 K/uL",
        trend: "improving",
      },
      {
        name: "Hemoglobin A1C",
        current: "5.8%",
        status: "normal",
        change: "-0.3%",
        normal: "<5.7%",
        trend: "improving",
      },
      {
        name: "Creatinine",
        current: "0.9 mg/dL",
        status: "normal",
        change: "0 mg/dL",
        normal: "0.6-1.2 mg/dL",
        trend: "stable",
      },
    ],
  },
}

// Sample health plans data
export const healthPlans = [
  {
    id: "1",
    title: "Blood Pressure Management",
    status: "moderate",
    currentValue: "132/85 mmHg",
    targetValue: "< 120/80 mmHg",
    progressExplanation: "Showing improvement with medication, but still above target range.",
  },
  {
    id: "2",
    title: "Weight Management",
    status: "good",
    currentValue: "158 lbs",
    targetValue: "150 lbs",
    progressExplanation: "Lost 7 pounds in the last 3 months. On track to reach target.",
  },
  {
    id: "3",
    title: "Cholesterol Management",
    status: "poor",
    currentValue: "LDL: 125 mg/dL",
    targetValue: "LDL: < 100 mg/dL",
    progressExplanation: "Limited progress despite medication. Consider dietary changes.",
  },
]

export const medicalRecords = [
  {
    id: "record1",
    type: "Lab Results",
    name: "Complete Blood Count",
    date: "2023-04-15",
    provider: "VitaHub Medical Center",
    doctor: "Dr. Sarah Johnson",
    status: "Abnormal",
    summary: "White blood cell count elevated. All other parameters within normal range.",
    fileUrl: "/documents/cbc-20230415.pdf",
  },
  {
    id: "record2",
    type: "Imaging",
    name: "Chest X-Ray",
    date: "2023-03-22",
    provider: "VitaHub Imaging Center",
    doctor: "Dr. Michael Chen",
    status: "Normal",
    summary: "No abnormalities detected. Lungs clear.",
    fileUrl: "/documents/chest-xray-20230322.pdf",
    imageUrl: "/images/chest-xray-sample.png",
  },
  {
    id: "record3",
    type: "Lab Results",
    name: "Lipid Panel",
    date: "2023-02-10",
    provider: "VitaHub Medical Center",
    doctor: "Dr. Sarah Johnson",
    status: "Abnormal",
    summary: "Total cholesterol and LDL elevated. HDL and triglycerides within normal range.",
    fileUrl: "/documents/lipid-20230210.pdf",
  },
  {
    id: "record4",
    type: "Visit Summary",
    name: "Annual Physical",
    date: "2023-01-15",
    provider: "VitaHub Medical Center",
    doctor: "Dr. Sarah Johnson",
    status: "Completed",
    summary:
      "Annual physical examination. Blood pressure elevated. Weight slightly above ideal range. Recommended lifestyle modifications and medication adjustment.",
    fileUrl: "/documents/annual-physical-20230115.pdf",
  },
  {
    id: "record5",
    type: "Imaging",
    name: "Abdominal Ultrasound",
    date: "2023-02-05",
    provider: "VitaHub Medical Center",
    doctor: "Dr. Sarah Johnson",
    status: "Normal",
    summary: "Liver, gallbladder, pancreas, and spleen appear normal. No abnormalities detected.",
    fileUrl: "/documents/abdominal-us-20230205.pdf",
    imageUrl: "/images/abdominal-us-sample.png",
  },
]

// Add new health records data
export const healthRecordsData = {
  bodyComposition: {
    summary:
      "Your body composition metrics show positive trends over the past 6 months. Body fat percentage has decreased by 2.3%, while muscle mass has increased by 1.5%. Continue with your current exercise regimen and protein intake to maintain this progress.",
    metrics: [
      {
        name: "Body Fat",
        current: "24%",
        status: "improving",
        change: "-2.3%",
        data: [
          { date: "2023-01-15", value: 26.3 },
          { date: "2023-02-15", value: 25.8 },
          { date: "2023-03-15", value: 25.2 },
          { date: "2023-04-15", value: 24.7 },
          { date: "2023-05-15", value: 24.0 },
        ],
      },
      {
        name: "Muscle Mass",
        current: "32%",
        status: "improving",
        change: "+1.5%",
        data: [
          { date: "2023-01-15", value: 30.5 },
          { date: "2023-02-15", value: 30.9 },
          { date: "2023-03-15", value: 31.2 },
          { date: "2023-04-15", value: 31.6 },
          { date: "2023-05-15", value: 32.0 },
        ],
      },
      {
        name: "Waist Circumference",
        current: "32 inches",
        status: "improving",
        change: "-2 inches",
        data: [
          { date: "2023-01-15", value: 34 },
          { date: "2023-02-15", value: 33.5 },
          { date: "2023-03-15", value: 33 },
          { date: "2023-04-15", value: 32.5 },
          { date: "2023-05-15", value: 32 },
        ],
      },
      {
        name: "BMI",
        current: "26.2",
        status: "improving",
        change: "-1.1",
        data: [
          { date: "2023-01-15", value: 27.3 },
          { date: "2023-02-15", value: 27.0 },
          { date: "2023-03-15", value: 26.7 },
          { date: "2023-04-15", value: 26.4 },
          { date: "2023-05-15", value: 26.2 },
        ],
      },
    ],
  },
  lifestyle: {
    summary:
      "Your lifestyle metrics indicate good sleep quality but insufficient daily activity. Your average of 6,200 steps is below the recommended 10,000 steps per day. Consider increasing your daily walks and structured exercise sessions to improve cardiovascular health and support your weight management goals.",
    metrics: [
      {
        name: "Sleep",
        current: "7.2 hours",
        status: "stable",
        change: "+0.2 hours",
        data: [
          { date: "2023-05-10", value: 7.1, quality: "Good" },
          { date: "2023-05-11", value: 6.8, quality: "Fair" },
          { date: "2023-05-12", value: 7.5, quality: "Good" },
          { date: "2023-05-13", value: 7.2, quality: "Good" },
          { date: "2023-05-14", value: 7.0, quality: "Good" },
          { date: "2023-05-15", value: 7.6, quality: "Excellent" },
          { date: "2023-05-16", value: 7.2, quality: "Good" },
        ],
      },
      {
        name: "Steps",
        current: "6,200",
        status: "needs improvement",
        change: "+800",
        data: [
          { date: "2023-05-10", value: 5200 },
          { date: "2023-05-11", value: 5800 },
          { date: "2023-05-12", value: 6500 },
          { date: "2023-05-13", value: 7200 },
          { date: "2023-05-14", value: 4800 },
          { date: "2023-05-15", value: 6900 },
          { date: "2023-05-16", value: 6200 },
        ],
      },
      {
        name: "Workouts",
        current: "3 per week",
        status: "good",
        change: "+1",
        data: [
          { date: "2023-05-01", type: "Cardio", duration: 30, calories: 250 },
          { date: "2023-05-03", type: "Strength", duration: 45, calories: 320 },
          { date: "2023-05-05", type: "Cardio", duration: 35, calories: 280 },
          { date: "2023-05-08", type: "Strength", duration: 40, calories: 300 },
          { date: "2023-05-10", type: "Cardio", duration: 30, calories: 245 },
          { date: "2023-05-12", type: "Strength", duration: 50, calories: 350 },
        ],
      },
    ],
  },
  vitals: {
    summary:
      "Your vital signs are generally within normal ranges, though your blood pressure remains slightly elevated. Your heart rate variability has improved, suggesting better cardiovascular fitness. Continue monitoring your blood pressure daily and maintain your medication regimen.",
    metrics: [
      {
        name: "Heart Rate",
        current: "68 bpm",
        status: "normal",
        change: "-3 bpm",
        data: [
          { date: "2023-05-10", value: 72 },
          { date: "2023-05-11", value: 70 },
          { date: "2023-05-12", value: 71 },
          { date: "2023-05-13", value: 69 },
          { date: "2023-05-14", value: 67 },
          { date: "2023-05-15", value: 68 },
          { date: "2023-05-16", value: 68 },
        ],
      },
      {
        name: "Blood Pressure",
        current: "132/85 mmHg",
        status: "elevated",
        change: "-6/-3 mmHg",
        data: [
          { date: "2023-01-15", systolic: 145, diastolic: 92 },
          { date: "2023-02-15", systolic: 142, diastolic: 90 },
          { date: "2023-03-15", systolic: 138, diastolic: 88 },
          { date: "2023-04-15", systolic: 135, diastolic: 87 },
          { date: "2023-05-15", systolic: 132, diastolic: 85 },
        ],
      },
      {
        name: "Oxygen Saturation",
        current: "98%",
        status: "normal",
        change: "+1%",
        data: [
          { date: "2023-05-10", value: 97 },
          { date: "2023-05-11", value: 97 },
          { date: "2023-05-12", value: 98 },
          { date: "2023-05-13", value: 98 },
          { date: "2023-05-14", value: 97 },
          { date: "2023-05-15", value: 98 },
          { date: "2023-05-16", value: 98 },
        ],
      },
    ],
    ecgResults: [
      {
        date: "2023-04-10",
        result: "Normal sinus rhythm",
        doctor: "Dr. Michael Chen",
        fileUrl: "/documents/ecg-20230410.pdf",
      },
      {
        date: "2023-01-15",
        result: "Normal sinus rhythm",
        doctor: "Dr. Michael Chen",
        fileUrl: "/documents/ecg-20230115.pdf",
      },
    ],
    heartSounds: [
      {
        date: "2023-04-10",
        result: "Normal S1 and S2, no murmurs",
        doctor: "Dr. Michael Chen",
        fileUrl: "/documents/heart-sounds-20230410.mp3",
      },
    ],
  },
  blood: {
    summary:
      "Your blood test results show improvement in cholesterol levels, though LDL remains slightly elevated. Your glucose levels have normalized, indicating good response to your current treatment plan. Continue with your medication regimen and dietary modifications to further improve lipid profile.",
    panels: [
      {
        name: "Complete Blood Count",
        date: "2023-04-15",
        fileUrl: "/documents/cbc-20230415.pdf",
        metrics: [
          { name: "White Blood Cells", value: "11.2", unit: "K/uL", status: "abnormal", range: "4.5-10.0" },
          { name: "Red Blood Cells", value: "4.8", unit: "M/uL", status: "normal", range: "4.5-5.5" },
          { name: "Hemoglobin", value: "14.2", unit: "g/dL", status: "normal", range: "13.5-17.5" },
          { name: "Hematocrit", value: "42", unit: "%", status: "normal", range: "41-50" },
          { name: "Platelets", value: "250", unit: "K/uL", status: "normal", range: "150-450" },
        ],
      },
      {
        name: "Lipid Panel",
        date: "2023-02-10",
        fileUrl: "/documents/lipid-20230210.pdf",
        metrics: [
          { name: "Total Cholesterol", value: "210", unit: "mg/dL", status: "abnormal", range: "<200" },
          { name: "LDL Cholesterol", value: "135", unit: "mg/dL", status: "abnormal", range: "<100" },
          { name: "HDL Cholesterol", value: "46", unit: "mg/dL", status: "normal", range: ">40" },
          { name: "Triglycerides", value: "145", unit: "mg/dL", status: "normal", range: "<150" },
        ],
      },
      {
        name: "Comprehensive Metabolic Panel",
        date: "2023-04-15",
        fileUrl: "/documents/cmp-20230415.pdf",
        metrics: [
          { name: "Glucose", value: "98", unit: "mg/dL", status: "normal", range: "70-99" },
          { name: "BUN", value: "15", unit: "mg/dL", status: "normal", range: "7-20" },
          { name: "Creatinine", value: "0.9", unit: "mg/dL", status: "normal", range: "0.6-1.2" },
          { name: "Sodium", value: "140", unit: "mmol/L", status: "normal", range: "136-145" },
          { name: "Potassium", value: "4.0", unit: "mmol/L", status: "normal", range: "3.5-5.1" },
          { name: "Calcium", value: "9.5", unit: "mg/dL", status: "normal", range: "8.5-10.2" },
        ],
      },
      {
        name: "Hemoglobin A1C",
        date: "2023-04-15",
        fileUrl: "/documents/a1c-20230415.pdf",
        metrics: [{ name: "HbA1c", value: "5.8", unit: "%", status: "normal", range: "<5.7" }],
      },
    ],
  },
  images: {
    summary:
      "Your imaging studies show no significant abnormalities. The chest X-ray from March shows clear lung fields and normal heart size. The abdominal ultrasound reveals a normal liver size with no evidence of fatty infiltration, which is an improvement from your previous study.",
    studies: [
      {
        name: "Chest X-Ray",
        date: "2023-03-22",
        type: "X-Ray",
        bodyPart: "Chest",
        result: "Normal",
        doctor: "Dr. Michael Chen",
        facility: "VitaHub Imaging Center",
        notes: "No abnormalities detected. Lungs clear.",
        fileUrl: "/documents/chest-xray-20230322.pdf",
        imageUrl: "/images/chest-xray-sample.png",
      },
      {
        name: "Abdominal Ultrasound",
        date: "2023-02-05",
        type: "Ultrasound",
        bodyPart: "Abdomen",
        result: "Normal",
        doctor: "Dr. Sarah Johnson",
        facility: "VitaHub Medical Center",
        notes: "Liver, gallbladder, pancreas, and spleen appear normal. No abnormalities detected.",
        fileUrl: "/documents/abdominal-us-20230205.pdf",
        imageUrl: "/images/abdominal-us-sample.png",
      },
      {
        name: "Bone Density Scan",
        date: "2022-11-10",
        type: "DEXA",
        bodyPart: "Spine and Hip",
        result: "Normal",
        doctor: "Dr. Emily Rodriguez",
        facility: "VitaHub Specialty Clinic",
        notes: "Bone density within normal range for age. T-score: -0.5",
        fileUrl: "/documents/dexa-20221110.pdf",
        imageUrl: "/images/dexa-sample.png",
      },
    ],
  },
}

export const trackedMetrics = [
  {
    id: "metric-1",
    type: "Blood Pressure",
    name: "Blood Pressure",
    currentValue: "132/85",
    targetValue: "120/80",
    unit: "mmHg",
  },
  {
    id: "metric-2",
    type: "Blood Glucose",
    name: "Blood Glucose",
    currentValue: "98",
    targetValue: "<100",
    unit: "mg/dL",
  },
  {
    id: "metric-3",
    type: "Weight",
    name: "Weight",
    currentValue: "158",
    targetValue: "150",
    unit: "lbs",
  },
  {
    id: "metric-4",
    type: "Cholesterol",
    name: "LDL Cholesterol",
    currentValue: "125",
    targetValue: "<100",
    unit: "mg/dL",
  },
  {
    id: "metric-5",
    type: "Body Fat",
    name: "Body Fat",
    currentValue: "24",
    targetValue: "20",
    unit: "%",
  },
]
